// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Persistence;

namespace Shop.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20190713215852_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Shop.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "giovanna.moen@upton.info",
                            Name = "Candido Koepp"
                        },
                        new
                        {
                            Id = 2,
                            Email = "joan.maggio@deckowgreenfelder.us",
                            Name = "Bradford Reynolds"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maximilian_wiza@ankunding.ca",
                            Name = "Trystan Gottlieb"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ocie@rohan.info",
                            Name = "Larry Strosin"
                        },
                        new
                        {
                            Id = 5,
                            Email = "melvin.marvin@cartwright.info",
                            Name = "Isaias Collins"
                        },
                        new
                        {
                            Id = 6,
                            Email = "damian.johnson@bogan.com",
                            Name = "Camylle King"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mireya@kuvalis.biz",
                            Name = "Toney Rutherford"
                        },
                        new
                        {
                            Id = 8,
                            Email = "quinten@gleasongreenholt.co.uk",
                            Name = "Jasen Jacobs"
                        },
                        new
                        {
                            Id = 9,
                            Email = "gloria.johnson@littel.us",
                            Name = "Celestine Bogisich PhD"
                        },
                        new
                        {
                            Id = 10,
                            Email = "rita_gislason@powlowski.name",
                            Name = "Elmer Frami"
                        },
                        new
                        {
                            Id = 11,
                            Email = "mike@corkery.name",
                            Name = "Javier Rohan"
                        },
                        new
                        {
                            Id = 12,
                            Email = "general@gusikowski.uk",
                            Name = "Bessie Muller"
                        },
                        new
                        {
                            Id = 13,
                            Email = "adele@parisian.co.uk",
                            Name = "Letitia Rogahn"
                        },
                        new
                        {
                            Id = 14,
                            Email = "nola_pollich@crooks.biz",
                            Name = "Jayda Lueilwitz IV"
                        },
                        new
                        {
                            Id = 15,
                            Email = "amara@lueilwitzmann.ca",
                            Name = "Delphia Schuster PhD"
                        },
                        new
                        {
                            Id = 16,
                            Email = "esta_ohara@mcglynn.info",
                            Name = "Madalyn Breitenberg"
                        },
                        new
                        {
                            Id = 17,
                            Email = "maye.koelpin@blanda.co.uk",
                            Name = "Dr. Hettie Towne"
                        },
                        new
                        {
                            Id = 18,
                            Email = "david_bode@ryan.ca",
                            Name = "Aurelie Hickle"
                        },
                        new
                        {
                            Id = 19,
                            Email = "christina@baumbach.info",
                            Name = "Dr. Gennaro Haag"
                        },
                        new
                        {
                            Id = 20,
                            Email = "waldo@hegmanncorwin.co.uk",
                            Name = "Benedict Hoeger"
                        },
                        new
                        {
                            Id = 21,
                            Email = "einar_wintheiser@jerde.name",
                            Name = "Jason Jenkins"
                        },
                        new
                        {
                            Id = 22,
                            Email = "delilah.bartell@wisozk.uk",
                            Name = "Miss Dixie Johnson"
                        },
                        new
                        {
                            Id = 23,
                            Email = "justyn.hilpert@waelchi.co.uk",
                            Name = "Uriah Yundt"
                        },
                        new
                        {
                            Id = 24,
                            Email = "jalyn.mueller@bernhard.uk",
                            Name = "Garland Borer"
                        },
                        new
                        {
                            Id = 25,
                            Email = "blair_mcglynn@walsheffertz.us",
                            Name = "Dr. Winfield Gerhold"
                        },
                        new
                        {
                            Id = 26,
                            Email = "tremaine@bashirian.com",
                            Name = "Willa Goldner"
                        },
                        new
                        {
                            Id = 27,
                            Email = "kenton_hegmann@johns.co.uk",
                            Name = "Leopold Cronin"
                        },
                        new
                        {
                            Id = 28,
                            Email = "beryl@schmitt.biz",
                            Name = "Sarah Luettgen"
                        },
                        new
                        {
                            Id = 29,
                            Email = "jaylon@kozey.us",
                            Name = "Carolyn Rodriguez"
                        },
                        new
                        {
                            Id = 30,
                            Email = "cali.bradtke@lowevolkman.com",
                            Name = "Jan Roberts"
                        },
                        new
                        {
                            Id = 31,
                            Email = "bernita@stracke.com",
                            Name = "Joannie Rogahn I"
                        },
                        new
                        {
                            Id = 32,
                            Email = "issac@hettingerboehm.info",
                            Name = "Hal Kohler"
                        },
                        new
                        {
                            Id = 33,
                            Email = "maddison_treutel@vandervortankunding.uk",
                            Name = "Jeromy Casper"
                        },
                        new
                        {
                            Id = 34,
                            Email = "harold@feeneyhilpert.uk",
                            Name = "Valentina Blick IV"
                        },
                        new
                        {
                            Id = 35,
                            Email = "weldon.kuvalis@walker.uk",
                            Name = "Whitney Haag"
                        },
                        new
                        {
                            Id = 36,
                            Email = "kenny@effertz.name",
                            Name = "Mrs. Madge Hoeger"
                        },
                        new
                        {
                            Id = 37,
                            Email = "esteban_yost@torphy.biz",
                            Name = "Karl Wyman"
                        },
                        new
                        {
                            Id = 38,
                            Email = "antonetta_kerluke@jerdeyundt.us",
                            Name = "Desmond Larson"
                        },
                        new
                        {
                            Id = 39,
                            Email = "santos_halvorson@yost.biz",
                            Name = "Otha Sipes"
                        },
                        new
                        {
                            Id = 40,
                            Email = "kendall@torp.info",
                            Name = "Nona Medhurst III"
                        },
                        new
                        {
                            Id = 41,
                            Email = "kendrick@torphy.info",
                            Name = "Meredith Buckridge"
                        },
                        new
                        {
                            Id = 42,
                            Email = "colton@murazik.biz",
                            Name = "Virgie Kris"
                        },
                        new
                        {
                            Id = 43,
                            Email = "lavinia@beckerkozey.com",
                            Name = "Buddy Lowe"
                        },
                        new
                        {
                            Id = 44,
                            Email = "juliana@balistrericartwright.ca",
                            Name = "Rhiannon Jakubowski"
                        },
                        new
                        {
                            Id = 45,
                            Email = "chaz@dietrichpouros.biz",
                            Name = "Dallas Green"
                        },
                        new
                        {
                            Id = 46,
                            Email = "jeramy@cummerata.com",
                            Name = "Gisselle Reichel"
                        },
                        new
                        {
                            Id = 47,
                            Email = "katherine_hintz@kris.uk",
                            Name = "Jorge Schaden"
                        },
                        new
                        {
                            Id = 48,
                            Email = "hilda_wintheiser@champlin.biz",
                            Name = "Lamont Batz II"
                        },
                        new
                        {
                            Id = 49,
                            Email = "ethan@wehnerokeefe.name",
                            Name = "Arthur Leffler"
                        },
                        new
                        {
                            Id = 50,
                            Email = "melyna_keeling@heidenreich.biz",
                            Name = "Muhammad Bins"
                        },
                        new
                        {
                            Id = 51,
                            Email = "ricardo@armstrong.us",
                            Name = "Crystel Christiansen II"
                        },
                        new
                        {
                            Id = 52,
                            Email = "bernice@okeefe.name",
                            Name = "Blake Conroy"
                        },
                        new
                        {
                            Id = 53,
                            Email = "violet.gleichner@johnston.uk",
                            Name = "Justina Heller"
                        },
                        new
                        {
                            Id = 54,
                            Email = "missouri@runte.biz",
                            Name = "Dr. Brett Stroman"
                        },
                        new
                        {
                            Id = 55,
                            Email = "kennith.hand@pourosshields.name",
                            Name = "Robbie Kozey IV"
                        },
                        new
                        {
                            Id = 56,
                            Email = "gaetano@lynch.ca",
                            Name = "Mayra Stracke"
                        },
                        new
                        {
                            Id = 57,
                            Email = "lauryn@mclaughlin.biz",
                            Name = "Dr. Kailyn Denesik"
                        },
                        new
                        {
                            Id = 58,
                            Email = "jewell@prosaccojast.co.uk",
                            Name = "Ezekiel Larkin"
                        },
                        new
                        {
                            Id = 59,
                            Email = "joel@abshirechamplin.us",
                            Name = "Celine McGlynn"
                        },
                        new
                        {
                            Id = 60,
                            Email = "lennie@murray.ca",
                            Name = "Corene Corwin"
                        },
                        new
                        {
                            Id = 61,
                            Email = "merlin@runolfsson.us",
                            Name = "Lera Tromp"
                        },
                        new
                        {
                            Id = 62,
                            Email = "lucas.vandervort@funk.ca",
                            Name = "Sarah Doyle"
                        },
                        new
                        {
                            Id = 63,
                            Email = "sven@moorerippin.info",
                            Name = "Kristopher Ferry"
                        },
                        new
                        {
                            Id = 64,
                            Email = "morris@runolfssonwilkinson.name",
                            Name = "Kip Von"
                        },
                        new
                        {
                            Id = 65,
                            Email = "dashawn.effertz@langluettgen.biz",
                            Name = "Nakia Bins"
                        },
                        new
                        {
                            Id = 66,
                            Email = "wilford.bartell@croninschneider.ca",
                            Name = "Gay Lueilwitz"
                        },
                        new
                        {
                            Id = 67,
                            Email = "edmund@upton.name",
                            Name = "Lilian Lesch Sr."
                        },
                        new
                        {
                            Id = 68,
                            Email = "torrey.rosenbaum@lubowitz.co.uk",
                            Name = "Gilbert Weber"
                        },
                        new
                        {
                            Id = 69,
                            Email = "lue@breitenbergschinner.co.uk",
                            Name = "Mrs. Aisha White"
                        },
                        new
                        {
                            Id = 70,
                            Email = "austin@walsh.ca",
                            Name = "Kyler Kirlin"
                        },
                        new
                        {
                            Id = 71,
                            Email = "catherine.kovacek@parker.us",
                            Name = "Katlynn Rowe"
                        },
                        new
                        {
                            Id = 72,
                            Email = "jazmin_goodwin@lindgrengislason.ca",
                            Name = "Kattie Boyle"
                        },
                        new
                        {
                            Id = 73,
                            Email = "americo@friesen.name",
                            Name = "Mrs. Elnora Auer"
                        },
                        new
                        {
                            Id = 74,
                            Email = "gail@von.info",
                            Name = "Jessyca Kuhlman"
                        },
                        new
                        {
                            Id = 75,
                            Email = "sean@haneveum.ca",
                            Name = "Jayme Schuster DDS"
                        },
                        new
                        {
                            Id = 76,
                            Email = "mathilde.parker@heaneykeeling.us",
                            Name = "Mrs. Aditya Langosh"
                        },
                        new
                        {
                            Id = 77,
                            Email = "ashlynn.huels@johnsonstanton.info",
                            Name = "Eudora Boyer"
                        },
                        new
                        {
                            Id = 78,
                            Email = "colten@daugherty.biz",
                            Name = "Robbie Raynor"
                        },
                        new
                        {
                            Id = 79,
                            Email = "whitney@parisian.us",
                            Name = "Raul Carter"
                        },
                        new
                        {
                            Id = 80,
                            Email = "mina@schaden.uk",
                            Name = "Eveline Terry Sr."
                        },
                        new
                        {
                            Id = 81,
                            Email = "roger.west@flatley.biz",
                            Name = "Delmer Macejkovic I"
                        },
                        new
                        {
                            Id = 82,
                            Email = "jacynthe@reichel.biz",
                            Name = "Ms. Wilber Brown"
                        },
                        new
                        {
                            Id = 83,
                            Email = "jaydon@hudson.com",
                            Name = "Verner Muller"
                        },
                        new
                        {
                            Id = 84,
                            Email = "sonny@roobjenkins.co.uk",
                            Name = "Kenny Luettgen I"
                        },
                        new
                        {
                            Id = 85,
                            Email = "vida@satterfield.com",
                            Name = "Robbie Ebert"
                        },
                        new
                        {
                            Id = 86,
                            Email = "raul_eichmann@koepp.info",
                            Name = "Wilburn Osinski"
                        },
                        new
                        {
                            Id = 87,
                            Email = "verdie.stracke@macejkovic.info",
                            Name = "Jordi Kuhn"
                        },
                        new
                        {
                            Id = 88,
                            Email = "laila.ritchie@ratke.info",
                            Name = "Madisen Medhurst"
                        },
                        new
                        {
                            Id = 89,
                            Email = "hipolito_parker@green.com",
                            Name = "Claud Tremblay"
                        },
                        new
                        {
                            Id = 90,
                            Email = "ada@volkman.uk",
                            Name = "Emma Rau"
                        },
                        new
                        {
                            Id = 91,
                            Email = "dorothy@wolf.com",
                            Name = "Quinn Doyle"
                        },
                        new
                        {
                            Id = 92,
                            Email = "myah.powlowski@schimmel.com",
                            Name = "Madisen Conn"
                        },
                        new
                        {
                            Id = 93,
                            Email = "frieda@goodwin.uk",
                            Name = "Wendy Osinski"
                        },
                        new
                        {
                            Id = 94,
                            Email = "rafaela@yundtrunte.us",
                            Name = "Ms. Duncan Stehr"
                        },
                        new
                        {
                            Id = 95,
                            Email = "syble.shields@murazikklein.name",
                            Name = "Layne Beer Sr."
                        },
                        new
                        {
                            Id = 96,
                            Email = "zelda.zemlak@cormier.com",
                            Name = "Jayce Mueller"
                        },
                        new
                        {
                            Id = 97,
                            Email = "timothy@quigleygreenfelder.uk",
                            Name = "Elvie Hirthe II"
                        },
                        new
                        {
                            Id = 98,
                            Email = "elliott@grimes.uk",
                            Name = "Lourdes Schuster PhD"
                        },
                        new
                        {
                            Id = 99,
                            Email = "daren_schulist@ziemannanderson.com",
                            Name = "Ashton Torp"
                        },
                        new
                        {
                            Id = 100,
                            Email = "dennis_romaguera@okeefeconn.biz",
                            Name = "Madilyn Swaniawski"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("CustomerId");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 6, 14, 0, 58, 51, 671, DateTimeKind.Local).AddTicks(3109),
                            CustomerId = 94,
                            Price = 17341.910m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2018, 10, 12, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 93,
                            Price = 54815.1872m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2018, 12, 8, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 36,
                            Price = 69457.1421m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 5, 26, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 35,
                            Price = 73337.2479m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2019, 5, 11, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 2,
                            Price = 9574.259m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2019, 6, 19, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 87,
                            Price = 92407.97m
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2019, 7, 5, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 54,
                            Price = 94439.638m
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2018, 12, 20, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 77,
                            Price = 9685.1614m
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2019, 4, 18, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 44,
                            Price = 10012.2415m
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2018, 12, 19, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 87,
                            Price = 83621.1m
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2019, 5, 31, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 30,
                            Price = 82608.1672m
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2019, 3, 15, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 7,
                            Price = 81017.2923m
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2019, 2, 23, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 24,
                            Price = 86248.1857m
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2019, 6, 19, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 52,
                            Price = 86021.3773m
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2018, 10, 17, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 43,
                            Price = 64791.3102m
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2019, 4, 19, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 17,
                            Price = 7863.1826m
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2019, 3, 21, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 20,
                            Price = 51071.1613m
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2019, 5, 7, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 53,
                            Price = 96228.2272m
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2019, 6, 10, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 61,
                            Price = 86159.615m
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2019, 5, 10, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 60,
                            Price = 28262.831m
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2018, 11, 12, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 85,
                            Price = 46148.367m
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2018, 11, 4, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 7,
                            Price = 20297.539m
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2019, 3, 5, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 47,
                            Price = 7807.3462m
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2018, 12, 21, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 7,
                            Price = 92630.1322m
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2019, 5, 20, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 69,
                            Price = 18500.2869m
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2019, 5, 9, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 76,
                            Price = 37210.2334m
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2018, 11, 9, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 23,
                            Price = 33014.827m
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2018, 9, 29, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 77,
                            Price = 56857.3021m
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2018, 11, 17, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 1,
                            Price = 41735.3269m
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2018, 11, 19, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 25,
                            Price = 60558.920m
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2019, 2, 16, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 47,
                            Price = 49502.3160m
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2018, 11, 11, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 17,
                            Price = 97185.1280m
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2019, 4, 27, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 13,
                            Price = 98635.1869m
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2018, 10, 15, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 67,
                            Price = 51356.2164m
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2019, 3, 31, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 55,
                            Price = 19738.2115m
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2019, 2, 10, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 28,
                            Price = 54204.3785m
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2018, 9, 29, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 58,
                            Price = 32127.2513m
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2019, 2, 3, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 15,
                            Price = 53900.2936m
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2018, 12, 13, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 33,
                            Price = 21508.2700m
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2019, 5, 10, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 20,
                            Price = 65282.3987m
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2019, 5, 14, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 41,
                            Price = 53805.2118m
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2018, 12, 12, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 48,
                            Price = 75830.3722m
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2018, 10, 25, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 45,
                            Price = 40354.1979m
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2018, 11, 29, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 5,
                            Price = 12651.1215m
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2018, 12, 31, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 64,
                            Price = 83473.827m
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2019, 4, 10, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 99,
                            Price = 15073.177m
                        },
                        new
                        {
                            Id = 47,
                            CreatedDate = new DateTime(2018, 12, 10, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 26,
                            Price = 54815.209m
                        },
                        new
                        {
                            Id = 48,
                            CreatedDate = new DateTime(2019, 5, 31, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 60,
                            Price = 71286.2685m
                        },
                        new
                        {
                            Id = 49,
                            CreatedDate = new DateTime(2019, 1, 22, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 31,
                            Price = 12009.3531m
                        },
                        new
                        {
                            Id = 50,
                            CreatedDate = new DateTime(2018, 12, 24, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 84,
                            Price = 14862.2442m
                        },
                        new
                        {
                            Id = 51,
                            CreatedDate = new DateTime(2018, 10, 8, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 34,
                            Price = 35214.1540m
                        },
                        new
                        {
                            Id = 52,
                            CreatedDate = new DateTime(2019, 6, 2, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 94,
                            Price = 13322.2624m
                        },
                        new
                        {
                            Id = 53,
                            CreatedDate = new DateTime(2018, 11, 5, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 3,
                            Price = 17532.1702m
                        },
                        new
                        {
                            Id = 54,
                            CreatedDate = new DateTime(2019, 3, 18, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 12,
                            Price = 26238.2807m
                        },
                        new
                        {
                            Id = 55,
                            CreatedDate = new DateTime(2019, 6, 14, 0, 58, 51, 673, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 39,
                            Price = 66776.3337m
                        },
                        new
                        {
                            Id = 56,
                            CreatedDate = new DateTime(2019, 4, 27, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 1,
                            Price = 54026.2968m
                        },
                        new
                        {
                            Id = 57,
                            CreatedDate = new DateTime(2019, 2, 19, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 99,
                            Price = 16443.2435m
                        },
                        new
                        {
                            Id = 58,
                            CreatedDate = new DateTime(2019, 7, 1, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 83,
                            Price = 69214.3861m
                        },
                        new
                        {
                            Id = 59,
                            CreatedDate = new DateTime(2018, 9, 24, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 72,
                            Price = 3175.165m
                        },
                        new
                        {
                            Id = 60,
                            CreatedDate = new DateTime(2018, 9, 20, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 8,
                            Price = 91653.1965m
                        },
                        new
                        {
                            Id = 61,
                            CreatedDate = new DateTime(2019, 4, 28, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 59,
                            Price = 34089.838m
                        },
                        new
                        {
                            Id = 62,
                            CreatedDate = new DateTime(2019, 6, 24, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 94,
                            Price = 70633.3961m
                        },
                        new
                        {
                            Id = 63,
                            CreatedDate = new DateTime(2018, 10, 20, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 75,
                            Price = 37802.1990m
                        },
                        new
                        {
                            Id = 64,
                            CreatedDate = new DateTime(2019, 2, 15, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 81,
                            Price = 39820.1075m
                        },
                        new
                        {
                            Id = 65,
                            CreatedDate = new DateTime(2019, 5, 16, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 22,
                            Price = 91542.3470m
                        },
                        new
                        {
                            Id = 66,
                            CreatedDate = new DateTime(2019, 4, 6, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 7,
                            Price = 61403.1328m
                        },
                        new
                        {
                            Id = 67,
                            CreatedDate = new DateTime(2019, 5, 31, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 31,
                            Price = 52656.168m
                        },
                        new
                        {
                            Id = 68,
                            CreatedDate = new DateTime(2019, 1, 26, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 30,
                            Price = 64462.611m
                        },
                        new
                        {
                            Id = 69,
                            CreatedDate = new DateTime(2018, 12, 7, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 63,
                            Price = 39638.408m
                        },
                        new
                        {
                            Id = 70,
                            CreatedDate = new DateTime(2019, 3, 20, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 36,
                            Price = 75521.3911m
                        },
                        new
                        {
                            Id = 71,
                            CreatedDate = new DateTime(2019, 4, 8, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 57,
                            Price = 23258.1698m
                        },
                        new
                        {
                            Id = 72,
                            CreatedDate = new DateTime(2018, 11, 3, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 80,
                            Price = 63616.1m
                        },
                        new
                        {
                            Id = 73,
                            CreatedDate = new DateTime(2019, 2, 10, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 70,
                            Price = 66666.1634m
                        },
                        new
                        {
                            Id = 74,
                            CreatedDate = new DateTime(2018, 10, 19, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 66,
                            Price = 87990.3757m
                        },
                        new
                        {
                            Id = 75,
                            CreatedDate = new DateTime(2019, 7, 9, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 49,
                            Price = 36026.2989m
                        },
                        new
                        {
                            Id = 76,
                            CreatedDate = new DateTime(2019, 6, 13, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 11,
                            Price = 63965.315m
                        },
                        new
                        {
                            Id = 77,
                            CreatedDate = new DateTime(2018, 9, 28, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 11,
                            Price = 96633.2628m
                        },
                        new
                        {
                            Id = 78,
                            CreatedDate = new DateTime(2018, 12, 23, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 75,
                            Price = 26974.570m
                        },
                        new
                        {
                            Id = 79,
                            CreatedDate = new DateTime(2019, 7, 3, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 6,
                            Price = 67888.571m
                        },
                        new
                        {
                            Id = 80,
                            CreatedDate = new DateTime(2018, 10, 28, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 52,
                            Price = 27820.2710m
                        },
                        new
                        {
                            Id = 81,
                            CreatedDate = new DateTime(2019, 2, 14, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 34,
                            Price = 2752.3974m
                        },
                        new
                        {
                            Id = 82,
                            CreatedDate = new DateTime(2018, 12, 22, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 59,
                            Price = 78638.3200m
                        },
                        new
                        {
                            Id = 83,
                            CreatedDate = new DateTime(2019, 3, 20, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 3,
                            Price = 22039.832m
                        },
                        new
                        {
                            Id = 84,
                            CreatedDate = new DateTime(2019, 6, 7, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 31,
                            Price = 21559.489m
                        },
                        new
                        {
                            Id = 85,
                            CreatedDate = new DateTime(2018, 10, 29, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 43,
                            Price = 96418.2157m
                        },
                        new
                        {
                            Id = 86,
                            CreatedDate = new DateTime(2019, 3, 30, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 86,
                            Price = 56902.3718m
                        },
                        new
                        {
                            Id = 87,
                            CreatedDate = new DateTime(2018, 9, 24, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 81,
                            Price = 28609.3754m
                        },
                        new
                        {
                            Id = 88,
                            CreatedDate = new DateTime(2018, 10, 28, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 99,
                            Price = 25880.3664m
                        },
                        new
                        {
                            Id = 89,
                            CreatedDate = new DateTime(2018, 11, 13, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 98,
                            Price = 57345.2824m
                        },
                        new
                        {
                            Id = 90,
                            CreatedDate = new DateTime(2019, 6, 16, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 11,
                            Price = 32377.3877m
                        },
                        new
                        {
                            Id = 91,
                            CreatedDate = new DateTime(2019, 7, 4, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 79,
                            Price = 61777.1835m
                        },
                        new
                        {
                            Id = 92,
                            CreatedDate = new DateTime(2018, 10, 12, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 7,
                            Price = 90858.671m
                        },
                        new
                        {
                            Id = 93,
                            CreatedDate = new DateTime(2019, 1, 28, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 52,
                            Price = 22792.2141m
                        },
                        new
                        {
                            Id = 94,
                            CreatedDate = new DateTime(2018, 12, 11, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 74,
                            Price = 36585.3477m
                        },
                        new
                        {
                            Id = 95,
                            CreatedDate = new DateTime(2018, 9, 29, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 75,
                            Price = 77241.2008m
                        },
                        new
                        {
                            Id = 96,
                            CreatedDate = new DateTime(2019, 6, 3, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 2,
                            Price = 47393.1014m
                        },
                        new
                        {
                            Id = 97,
                            CreatedDate = new DateTime(2018, 11, 10, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 82,
                            Price = 82385.310m
                        },
                        new
                        {
                            Id = 98,
                            CreatedDate = new DateTime(2019, 3, 23, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 7,
                            Price = 95027.956m
                        },
                        new
                        {
                            Id = 99,
                            CreatedDate = new DateTime(2019, 1, 27, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 34,
                            Price = 63828.3343m
                        },
                        new
                        {
                            Id = 100,
                            CreatedDate = new DateTime(2019, 4, 8, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 75,
                            Price = 77990.1834m
                        },
                        new
                        {
                            Id = 101,
                            CreatedDate = new DateTime(2019, 5, 23, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 24,
                            Price = 19296.3030m
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2019, 5, 28, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 23,
                            Price = 97513.3283m
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2019, 3, 12, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 59,
                            Price = 17841.2839m
                        },
                        new
                        {
                            Id = 104,
                            CreatedDate = new DateTime(2019, 5, 18, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 60,
                            Price = 79267.110m
                        },
                        new
                        {
                            Id = 105,
                            CreatedDate = new DateTime(2019, 3, 31, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 52,
                            Price = 39841.1414m
                        },
                        new
                        {
                            Id = 106,
                            CreatedDate = new DateTime(2019, 6, 18, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 13,
                            Price = 56904.3891m
                        },
                        new
                        {
                            Id = 107,
                            CreatedDate = new DateTime(2019, 1, 7, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 12,
                            Price = 81899.1234m
                        },
                        new
                        {
                            Id = 108,
                            CreatedDate = new DateTime(2018, 10, 5, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 93,
                            Price = 5984.2274m
                        },
                        new
                        {
                            Id = 109,
                            CreatedDate = new DateTime(2019, 3, 22, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 23,
                            Price = 8493.2473m
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2018, 9, 19, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 97,
                            Price = 57224.2740m
                        },
                        new
                        {
                            Id = 111,
                            CreatedDate = new DateTime(2019, 4, 16, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 18,
                            Price = 84220.1385m
                        },
                        new
                        {
                            Id = 112,
                            CreatedDate = new DateTime(2018, 11, 15, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 100,
                            Price = 34983.1848m
                        },
                        new
                        {
                            Id = 113,
                            CreatedDate = new DateTime(2019, 7, 11, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 46,
                            Price = 6538.1261m
                        },
                        new
                        {
                            Id = 114,
                            CreatedDate = new DateTime(2019, 6, 9, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 10,
                            Price = 10582.833m
                        },
                        new
                        {
                            Id = 115,
                            CreatedDate = new DateTime(2019, 2, 16, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 24,
                            Price = 98844.79m
                        },
                        new
                        {
                            Id = 116,
                            CreatedDate = new DateTime(2019, 1, 22, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 45,
                            Price = 27792.2949m
                        },
                        new
                        {
                            Id = 117,
                            CreatedDate = new DateTime(2018, 12, 22, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 76,
                            Price = 92610.3460m
                        },
                        new
                        {
                            Id = 118,
                            CreatedDate = new DateTime(2018, 11, 26, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 50,
                            Price = 77649.3440m
                        },
                        new
                        {
                            Id = 119,
                            CreatedDate = new DateTime(2019, 1, 4, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 4,
                            Price = 48371.350m
                        },
                        new
                        {
                            Id = 120,
                            CreatedDate = new DateTime(2018, 11, 3, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 92,
                            Price = 98955.2071m
                        },
                        new
                        {
                            Id = 121,
                            CreatedDate = new DateTime(2019, 3, 31, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 20,
                            Price = 74258.1352m
                        },
                        new
                        {
                            Id = 122,
                            CreatedDate = new DateTime(2019, 4, 21, 0, 58, 51, 674, DateTimeKind.Local).AddTicks(3110),
                            CustomerId = 87,
                            Price = 47091.1675m
                        },
                        new
                        {
                            Id = 123,
                            CreatedDate = new DateTime(2018, 11, 30, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 21,
                            Price = 93304.2004m
                        },
                        new
                        {
                            Id = 124,
                            CreatedDate = new DateTime(2019, 1, 3, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 32,
                            Price = 43461.2060m
                        },
                        new
                        {
                            Id = 125,
                            CreatedDate = new DateTime(2019, 3, 29, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 88,
                            Price = 1775.1526m
                        },
                        new
                        {
                            Id = 126,
                            CreatedDate = new DateTime(2019, 3, 14, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 45,
                            Price = 15411.79m
                        },
                        new
                        {
                            Id = 127,
                            CreatedDate = new DateTime(2019, 4, 19, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 27,
                            Price = 26373.379m
                        },
                        new
                        {
                            Id = 128,
                            CreatedDate = new DateTime(2018, 11, 18, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 42,
                            Price = 61637.3386m
                        },
                        new
                        {
                            Id = 129,
                            CreatedDate = new DateTime(2018, 10, 7, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 30,
                            Price = 40781.2052m
                        },
                        new
                        {
                            Id = 130,
                            CreatedDate = new DateTime(2018, 10, 24, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 20,
                            Price = 75555.3452m
                        },
                        new
                        {
                            Id = 131,
                            CreatedDate = new DateTime(2019, 4, 21, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 33,
                            Price = 60414.2336m
                        },
                        new
                        {
                            Id = 132,
                            CreatedDate = new DateTime(2019, 1, 19, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 55,
                            Price = 3915.1514m
                        },
                        new
                        {
                            Id = 133,
                            CreatedDate = new DateTime(2019, 6, 9, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 36,
                            Price = 7560.3326m
                        },
                        new
                        {
                            Id = 134,
                            CreatedDate = new DateTime(2018, 12, 12, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 62,
                            Price = 4674.3815m
                        },
                        new
                        {
                            Id = 135,
                            CreatedDate = new DateTime(2018, 12, 18, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 58,
                            Price = 53223.798m
                        },
                        new
                        {
                            Id = 136,
                            CreatedDate = new DateTime(2019, 4, 1, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 32,
                            Price = 8492.3989m
                        },
                        new
                        {
                            Id = 137,
                            CreatedDate = new DateTime(2019, 4, 25, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 44,
                            Price = 62883.217m
                        },
                        new
                        {
                            Id = 138,
                            CreatedDate = new DateTime(2019, 5, 16, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 6,
                            Price = 94251.2015m
                        },
                        new
                        {
                            Id = 139,
                            CreatedDate = new DateTime(2018, 11, 25, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 25,
                            Price = 87532.3723m
                        },
                        new
                        {
                            Id = 140,
                            CreatedDate = new DateTime(2018, 11, 24, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 89,
                            Price = 52901.2257m
                        },
                        new
                        {
                            Id = 141,
                            CreatedDate = new DateTime(2018, 12, 8, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 85,
                            Price = 88079.2362m
                        },
                        new
                        {
                            Id = 142,
                            CreatedDate = new DateTime(2019, 7, 3, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 39,
                            Price = 19073.2427m
                        },
                        new
                        {
                            Id = 143,
                            CreatedDate = new DateTime(2019, 2, 18, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 91,
                            Price = 86562.1032m
                        },
                        new
                        {
                            Id = 144,
                            CreatedDate = new DateTime(2018, 11, 12, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 100,
                            Price = 47372.3325m
                        },
                        new
                        {
                            Id = 145,
                            CreatedDate = new DateTime(2018, 11, 17, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 95,
                            Price = 24879.3719m
                        },
                        new
                        {
                            Id = 146,
                            CreatedDate = new DateTime(2019, 5, 7, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 76,
                            Price = 45230.3882m
                        },
                        new
                        {
                            Id = 147,
                            CreatedDate = new DateTime(2018, 10, 14, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 29,
                            Price = 33208.506m
                        },
                        new
                        {
                            Id = 148,
                            CreatedDate = new DateTime(2019, 3, 3, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 46,
                            Price = 91379.633m
                        },
                        new
                        {
                            Id = 149,
                            CreatedDate = new DateTime(2019, 5, 7, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 28,
                            Price = 29908.369m
                        },
                        new
                        {
                            Id = 150,
                            CreatedDate = new DateTime(2019, 3, 21, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 70,
                            Price = 34328.405m
                        },
                        new
                        {
                            Id = 151,
                            CreatedDate = new DateTime(2019, 2, 27, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 26,
                            Price = 45433.1923m
                        },
                        new
                        {
                            Id = 152,
                            CreatedDate = new DateTime(2019, 6, 27, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 54,
                            Price = 98287.3272m
                        },
                        new
                        {
                            Id = 153,
                            CreatedDate = new DateTime(2018, 12, 5, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 49,
                            Price = 29669.627m
                        },
                        new
                        {
                            Id = 154,
                            CreatedDate = new DateTime(2018, 12, 11, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 43,
                            Price = 39103.837m
                        },
                        new
                        {
                            Id = 155,
                            CreatedDate = new DateTime(2018, 9, 26, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 1,
                            Price = 15226.449m
                        },
                        new
                        {
                            Id = 156,
                            CreatedDate = new DateTime(2018, 10, 19, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 30,
                            Price = 97135.1907m
                        },
                        new
                        {
                            Id = 157,
                            CreatedDate = new DateTime(2019, 3, 16, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 2,
                            Price = 98404.765m
                        },
                        new
                        {
                            Id = 158,
                            CreatedDate = new DateTime(2018, 11, 24, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 73,
                            Price = 98218.53m
                        },
                        new
                        {
                            Id = 159,
                            CreatedDate = new DateTime(2018, 11, 6, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 12,
                            Price = 39343.1729m
                        },
                        new
                        {
                            Id = 160,
                            CreatedDate = new DateTime(2018, 10, 4, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 47,
                            Price = 51302.3270m
                        },
                        new
                        {
                            Id = 161,
                            CreatedDate = new DateTime(2018, 11, 16, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 10,
                            Price = 35785.861m
                        },
                        new
                        {
                            Id = 162,
                            CreatedDate = new DateTime(2018, 11, 7, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 22,
                            Price = 70501.2409m
                        },
                        new
                        {
                            Id = 163,
                            CreatedDate = new DateTime(2019, 7, 12, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 9,
                            Price = 74739.457m
                        },
                        new
                        {
                            Id = 164,
                            CreatedDate = new DateTime(2019, 2, 14, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 9,
                            Price = 66519.2009m
                        },
                        new
                        {
                            Id = 165,
                            CreatedDate = new DateTime(2018, 12, 11, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 80,
                            Price = 14049.3136m
                        },
                        new
                        {
                            Id = 166,
                            CreatedDate = new DateTime(2018, 12, 14, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 48,
                            Price = 20487.3132m
                        },
                        new
                        {
                            Id = 167,
                            CreatedDate = new DateTime(2018, 12, 19, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 23,
                            Price = 58764.1710m
                        },
                        new
                        {
                            Id = 168,
                            CreatedDate = new DateTime(2019, 4, 16, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 21,
                            Price = 10996.1600m
                        },
                        new
                        {
                            Id = 169,
                            CreatedDate = new DateTime(2019, 3, 9, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 57,
                            Price = 60782.1490m
                        },
                        new
                        {
                            Id = 170,
                            CreatedDate = new DateTime(2019, 5, 31, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 92,
                            Price = 31011.2835m
                        },
                        new
                        {
                            Id = 171,
                            CreatedDate = new DateTime(2019, 4, 11, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 88,
                            Price = 86700.1057m
                        },
                        new
                        {
                            Id = 172,
                            CreatedDate = new DateTime(2019, 2, 18, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 3,
                            Price = 67904.545m
                        },
                        new
                        {
                            Id = 173,
                            CreatedDate = new DateTime(2018, 9, 18, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 28,
                            Price = 95842.3901m
                        },
                        new
                        {
                            Id = 174,
                            CreatedDate = new DateTime(2018, 10, 28, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 90,
                            Price = 98659.563m
                        },
                        new
                        {
                            Id = 175,
                            CreatedDate = new DateTime(2019, 6, 8, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 11,
                            Price = 14437.3601m
                        },
                        new
                        {
                            Id = 176,
                            CreatedDate = new DateTime(2019, 4, 11, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 21,
                            Price = 76495.3467m
                        },
                        new
                        {
                            Id = 177,
                            CreatedDate = new DateTime(2018, 11, 19, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 25,
                            Price = 57922.2102m
                        },
                        new
                        {
                            Id = 178,
                            CreatedDate = new DateTime(2018, 10, 5, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 28,
                            Price = 74360.955m
                        },
                        new
                        {
                            Id = 179,
                            CreatedDate = new DateTime(2018, 11, 3, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 56,
                            Price = 77576.1521m
                        },
                        new
                        {
                            Id = 180,
                            CreatedDate = new DateTime(2019, 6, 5, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 50,
                            Price = 7064.729m
                        },
                        new
                        {
                            Id = 181,
                            CreatedDate = new DateTime(2019, 2, 16, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 8,
                            Price = 49161.3555m
                        },
                        new
                        {
                            Id = 182,
                            CreatedDate = new DateTime(2018, 11, 3, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 90,
                            Price = 6894.1472m
                        },
                        new
                        {
                            Id = 183,
                            CreatedDate = new DateTime(2019, 1, 25, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 22,
                            Price = 90752.753m
                        },
                        new
                        {
                            Id = 184,
                            CreatedDate = new DateTime(2019, 1, 29, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 34,
                            Price = 88921.2226m
                        },
                        new
                        {
                            Id = 185,
                            CreatedDate = new DateTime(2019, 3, 9, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 89,
                            Price = 8128.2328m
                        },
                        new
                        {
                            Id = 186,
                            CreatedDate = new DateTime(2019, 5, 7, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 94,
                            Price = 40561.82m
                        },
                        new
                        {
                            Id = 187,
                            CreatedDate = new DateTime(2018, 11, 2, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 55,
                            Price = 12221.3216m
                        },
                        new
                        {
                            Id = 188,
                            CreatedDate = new DateTime(2019, 3, 17, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 8,
                            Price = 95052.374m
                        },
                        new
                        {
                            Id = 189,
                            CreatedDate = new DateTime(2018, 12, 4, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 10,
                            Price = 53636.2274m
                        },
                        new
                        {
                            Id = 190,
                            CreatedDate = new DateTime(2018, 11, 17, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 32,
                            Price = 64399.3087m
                        },
                        new
                        {
                            Id = 191,
                            CreatedDate = new DateTime(2018, 10, 4, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 42,
                            Price = 12766.2097m
                        },
                        new
                        {
                            Id = 192,
                            CreatedDate = new DateTime(2019, 2, 16, 0, 58, 51, 675, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 85,
                            Price = 35789.960m
                        },
                        new
                        {
                            Id = 193,
                            CreatedDate = new DateTime(2019, 3, 28, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 85,
                            Price = 1915.1352m
                        },
                        new
                        {
                            Id = 194,
                            CreatedDate = new DateTime(2018, 11, 9, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 21,
                            Price = 20384.247m
                        },
                        new
                        {
                            Id = 195,
                            CreatedDate = new DateTime(2018, 9, 25, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 48,
                            Price = 68392.3484m
                        },
                        new
                        {
                            Id = 196,
                            CreatedDate = new DateTime(2018, 10, 19, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 36,
                            Price = 62423.909m
                        },
                        new
                        {
                            Id = 197,
                            CreatedDate = new DateTime(2019, 7, 5, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 3,
                            Price = 30204.510m
                        },
                        new
                        {
                            Id = 198,
                            CreatedDate = new DateTime(2018, 9, 21, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 42,
                            Price = 21718.3912m
                        },
                        new
                        {
                            Id = 199,
                            CreatedDate = new DateTime(2019, 6, 15, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 71,
                            Price = 19533.1243m
                        },
                        new
                        {
                            Id = 200,
                            CreatedDate = new DateTime(2019, 6, 17, 0, 58, 51, 676, DateTimeKind.Local).AddTicks(3111),
                            CustomerId = 13,
                            Price = 22885.3080m
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
