// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Persistence;

namespace Shop.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20190714144949_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Shop.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kayley@mitchellkoss.com",
                            Name = "Dr. Hollis Lowe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "oren@mayert.biz",
                            Name = "Sydnee Moore"
                        },
                        new
                        {
                            Id = 3,
                            Email = "lonnie@beer.biz",
                            Name = "Rodger Roberts"
                        },
                        new
                        {
                            Id = 4,
                            Email = "geovanny.klocko@pfeffer.biz",
                            Name = "Ted Gleichner"
                        },
                        new
                        {
                            Id = 5,
                            Email = "otho@littlereichel.uk",
                            Name = "Mrs. Carroll Satterfield"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emely.shanahan@rogahn.ca",
                            Name = "Hayley Herzog"
                        },
                        new
                        {
                            Id = 7,
                            Email = "agnes@gleason.info",
                            Name = "Monte Hackett"
                        },
                        new
                        {
                            Id = 8,
                            Email = "kevin_frami@aufderhar.com",
                            Name = "Marcos Bins"
                        },
                        new
                        {
                            Id = 9,
                            Email = "dedrick.stamm@jacobsonweimann.ca",
                            Name = "Dallin Gusikowski IV"
                        },
                        new
                        {
                            Id = 10,
                            Email = "janiya@runolfsson.us",
                            Name = "Halle Hermiston"
                        },
                        new
                        {
                            Id = 11,
                            Email = "edmund_rodriguez@mcclure.info",
                            Name = "Luz Little"
                        },
                        new
                        {
                            Id = 12,
                            Email = "ramiro@rutherford.uk",
                            Name = "Genevieve Pfeffer"
                        },
                        new
                        {
                            Id = 13,
                            Email = "chelsea@effertzcormier.info",
                            Name = "Hellen Wilderman"
                        },
                        new
                        {
                            Id = 14,
                            Email = "robb_rolfson@mraz.co.uk",
                            Name = "Dereck Daniel"
                        },
                        new
                        {
                            Id = 15,
                            Email = "alexandre@abshire.name",
                            Name = "Miss Courtney Renner"
                        },
                        new
                        {
                            Id = 16,
                            Email = "kyler.lindgren@mitchellschoen.biz",
                            Name = "Sabrina Raynor I"
                        },
                        new
                        {
                            Id = 17,
                            Email = "betsy_beer@johns.biz",
                            Name = "Lemuel McClure"
                        },
                        new
                        {
                            Id = 18,
                            Email = "emerson_considine@wuckert.co.uk",
                            Name = "Name Kautzer"
                        },
                        new
                        {
                            Id = 19,
                            Email = "jonathon@schamberger.co.uk",
                            Name = "Mr. Fatima Crona"
                        },
                        new
                        {
                            Id = 20,
                            Email = "kay@mills.ca",
                            Name = "Bradford Sanford"
                        },
                        new
                        {
                            Id = 21,
                            Email = "rudy.graham@yundt.biz",
                            Name = "Juwan Bogan"
                        },
                        new
                        {
                            Id = 22,
                            Email = "hilton@larson.ca",
                            Name = "Coty Miller"
                        },
                        new
                        {
                            Id = 23,
                            Email = "elmira@simonis.info",
                            Name = "Dr. Gertrude Lebsack"
                        },
                        new
                        {
                            Id = 24,
                            Email = "kelley.roob@adams.ca",
                            Name = "Mathias Pfannerstill"
                        },
                        new
                        {
                            Id = 25,
                            Email = "julien@greenfelderbecker.info",
                            Name = "Alejandra Lubowitz"
                        },
                        new
                        {
                            Id = 26,
                            Email = "easton_predovic@stehr.com",
                            Name = "Mercedes Cole"
                        },
                        new
                        {
                            Id = 27,
                            Email = "adah@walkerwalsh.uk",
                            Name = "Zoey Nitzsche"
                        },
                        new
                        {
                            Id = 28,
                            Email = "deja@skiles.info",
                            Name = "Mrs. Shayne Walter"
                        },
                        new
                        {
                            Id = 29,
                            Email = "pinkie@reicherthuel.info",
                            Name = "Ora Doyle"
                        },
                        new
                        {
                            Id = 30,
                            Email = "winona@schneider.us",
                            Name = "Marvin Kilback"
                        },
                        new
                        {
                            Id = 31,
                            Email = "madelyn@mclaughlin.name",
                            Name = "Abdullah Miller"
                        },
                        new
                        {
                            Id = 32,
                            Email = "antonetta@muellerschimmel.biz",
                            Name = "Dr. Salvatore Wilderman"
                        },
                        new
                        {
                            Id = 33,
                            Email = "ana.hammes@rempel.uk",
                            Name = "Isac Schmitt"
                        },
                        new
                        {
                            Id = 34,
                            Email = "chelsie@cartwrightkassulke.uk",
                            Name = "Jamal Quitzon"
                        },
                        new
                        {
                            Id = 35,
                            Email = "zachary@ricebernhard.co.uk",
                            Name = "Ferne Schaefer"
                        },
                        new
                        {
                            Id = 36,
                            Email = "winston_douglas@hagenes.uk",
                            Name = "Keely Altenwerth"
                        },
                        new
                        {
                            Id = 37,
                            Email = "laverna@jacobiflatley.name",
                            Name = "Autumn Gislason"
                        },
                        new
                        {
                            Id = 38,
                            Email = "dahlia@botsfordankunding.com",
                            Name = "Baylee Kuphal"
                        },
                        new
                        {
                            Id = 39,
                            Email = "isaac.keebler@krajcik.co.uk",
                            Name = "Ms. Kurt Prohaska"
                        },
                        new
                        {
                            Id = 40,
                            Email = "assunta_rosenbaum@bernhardkuhn.com",
                            Name = "Ms. Walton Mertz"
                        },
                        new
                        {
                            Id = 41,
                            Email = "kip_dickens@franecki.co.uk",
                            Name = "Gladys Beer MD"
                        },
                        new
                        {
                            Id = 42,
                            Email = "norene@kuhn.co.uk",
                            Name = "Rebeka Schmeler"
                        },
                        new
                        {
                            Id = 43,
                            Email = "abe.jerde@lehnerbotsford.ca",
                            Name = "Gonzalo Mueller"
                        },
                        new
                        {
                            Id = 44,
                            Email = "candido_torphy@durgan.ca",
                            Name = "Amie Fay"
                        },
                        new
                        {
                            Id = 45,
                            Email = "lane_corkery@larkin.co.uk",
                            Name = "Ms. Hermina Glover"
                        },
                        new
                        {
                            Id = 46,
                            Email = "jeanette_klein@marvin.ca",
                            Name = "Susanna Baumbach PhD"
                        },
                        new
                        {
                            Id = 47,
                            Email = "keenan_donnelly@greenholtcorkery.co.uk",
                            Name = "Leonardo Auer"
                        },
                        new
                        {
                            Id = 48,
                            Email = "gerhard.balistreri@pfannerstill.ca",
                            Name = "Hailie Schuster"
                        },
                        new
                        {
                            Id = 49,
                            Email = "barney.hand@johnston.com",
                            Name = "Rylee Balistreri I"
                        },
                        new
                        {
                            Id = 50,
                            Email = "cayla_wilderman@weber.biz",
                            Name = "Brandyn Huel DVM"
                        },
                        new
                        {
                            Id = 51,
                            Email = "vince.kassulke@hessel.us",
                            Name = "Antoinette Parker"
                        },
                        new
                        {
                            Id = 52,
                            Email = "dejah_fahey@mohr.us",
                            Name = "Ava Harber"
                        },
                        new
                        {
                            Id = 53,
                            Email = "janie_kuhic@treutel.co.uk",
                            Name = "Annetta Doyle"
                        },
                        new
                        {
                            Id = 54,
                            Email = "suzanne@schroederwisoky.info",
                            Name = "Miss Fern Koch"
                        },
                        new
                        {
                            Id = 55,
                            Email = "willa@fritschturcotte.uk",
                            Name = "Wilfrid Bins"
                        },
                        new
                        {
                            Id = 56,
                            Email = "nikolas@willflatley.info",
                            Name = "Ms. Raoul Wuckert"
                        },
                        new
                        {
                            Id = 57,
                            Email = "else.toy@schmidt.com",
                            Name = "Marjolaine Mosciski DDS"
                        },
                        new
                        {
                            Id = 58,
                            Email = "dane@colemonahan.name",
                            Name = "Edythe Towne"
                        },
                        new
                        {
                            Id = 59,
                            Email = "mariano@olson.biz",
                            Name = "Zechariah Heathcote"
                        },
                        new
                        {
                            Id = 60,
                            Email = "mose.wyman@boehm.biz",
                            Name = "Uriel Collins"
                        },
                        new
                        {
                            Id = 61,
                            Email = "reuben@lebsack.ca",
                            Name = "Aletha Bradtke"
                        },
                        new
                        {
                            Id = 62,
                            Email = "marshall.schimmel@brakus.co.uk",
                            Name = "Dr. Lora Treutel"
                        },
                        new
                        {
                            Id = 63,
                            Email = "raven@rowekris.co.uk",
                            Name = "Trever Emmerich"
                        },
                        new
                        {
                            Id = 64,
                            Email = "lucious@carter.biz",
                            Name = "Bart Williamson"
                        },
                        new
                        {
                            Id = 65,
                            Email = "braden_bauch@kessler.uk",
                            Name = "Ryan Dach"
                        },
                        new
                        {
                            Id = 66,
                            Email = "johanna.abshire@stokes.ca",
                            Name = "Timothy Yost"
                        },
                        new
                        {
                            Id = 67,
                            Email = "karl_schiller@morissette.uk",
                            Name = "Nigel Reilly"
                        },
                        new
                        {
                            Id = 68,
                            Email = "lane@hudson.biz",
                            Name = "Mr. Felicita Dickinson"
                        },
                        new
                        {
                            Id = 69,
                            Email = "brennan_bruen@conroyraynor.com",
                            Name = "Chadrick Wiza"
                        },
                        new
                        {
                            Id = 70,
                            Email = "rhianna@flatleyoconnell.ca",
                            Name = "Mariela Yundt"
                        },
                        new
                        {
                            Id = 71,
                            Email = "ilene.wisozk@conn.co.uk",
                            Name = "Jakob Lang"
                        },
                        new
                        {
                            Id = 72,
                            Email = "maybelle_schamberger@bauch.com",
                            Name = "Roberto Cummerata"
                        },
                        new
                        {
                            Id = 73,
                            Email = "conor_ruecker@corkery.com",
                            Name = "Rozella Smith"
                        },
                        new
                        {
                            Id = 74,
                            Email = "eloise@runolfsdottir.co.uk",
                            Name = "Brannon Ondricka"
                        },
                        new
                        {
                            Id = 75,
                            Email = "roslyn.prohaska@mcglynnlangosh.ca",
                            Name = "Dariana Maggio PhD"
                        },
                        new
                        {
                            Id = 76,
                            Email = "jeanne_eichmann@schoenkassulke.us",
                            Name = "Randall Bashirian"
                        },
                        new
                        {
                            Id = 77,
                            Email = "lila.schumm@smitham.co.uk",
                            Name = "Valentina Batz"
                        },
                        new
                        {
                            Id = 78,
                            Email = "georgianna_nienow@powlowskibode.biz",
                            Name = "Lily Goldner"
                        },
                        new
                        {
                            Id = 79,
                            Email = "maybelle@abbottzboncak.name",
                            Name = "Rita Stark"
                        },
                        new
                        {
                            Id = 80,
                            Email = "ottis_labadie@nicolas.biz",
                            Name = "Michale Towne Jr."
                        },
                        new
                        {
                            Id = 81,
                            Email = "estell@hoegerhickle.biz",
                            Name = "Christian Gaylord"
                        },
                        new
                        {
                            Id = 82,
                            Email = "constantin.marvin@harber.name",
                            Name = "Mossie Gerlach PhD"
                        },
                        new
                        {
                            Id = 83,
                            Email = "toy@torpchristiansen.us",
                            Name = "Romaine Reynolds"
                        },
                        new
                        {
                            Id = 84,
                            Email = "laurine_hilll@mosciski.co.uk",
                            Name = "Miss Alessia Lindgren"
                        },
                        new
                        {
                            Id = 85,
                            Email = "kody@watsica.name",
                            Name = "Loma Davis"
                        },
                        new
                        {
                            Id = 86,
                            Email = "marion@reilly.uk",
                            Name = "Randi Hammes"
                        },
                        new
                        {
                            Id = 87,
                            Email = "ramona@lueilwitz.name",
                            Name = "Samanta Osinski"
                        },
                        new
                        {
                            Id = 88,
                            Email = "murl@stiedemann.biz",
                            Name = "Jillian Pagac"
                        },
                        new
                        {
                            Id = 89,
                            Email = "pearline.renner@davis.us",
                            Name = "Dr. Clotilde Weber"
                        },
                        new
                        {
                            Id = 90,
                            Email = "else@hilll.co.uk",
                            Name = "Dr. Brooks McDermott"
                        },
                        new
                        {
                            Id = 91,
                            Email = "emily_blick@lueilwitzmayert.co.uk",
                            Name = "Yesenia Ankunding"
                        },
                        new
                        {
                            Id = 92,
                            Email = "terrence_monahan@faygerhold.name",
                            Name = "Miss Judge Jast"
                        },
                        new
                        {
                            Id = 93,
                            Email = "markus@weissnatprosacco.ca",
                            Name = "Grayson Spinka Jr."
                        },
                        new
                        {
                            Id = 94,
                            Email = "vance.mertz@sporermuller.us",
                            Name = "Janie Durgan"
                        },
                        new
                        {
                            Id = 95,
                            Email = "charley.hudson@rosenbaumquitzon.info",
                            Name = "Art Bernier"
                        },
                        new
                        {
                            Id = 96,
                            Email = "jovani@schmeler.us",
                            Name = "Zelma Torp III"
                        },
                        new
                        {
                            Id = 97,
                            Email = "addison@douglas.uk",
                            Name = "Nyah Becker"
                        },
                        new
                        {
                            Id = 98,
                            Email = "oleta@wittingklocko.com",
                            Name = "Lincoln Stamm"
                        },
                        new
                        {
                            Id = 99,
                            Email = "deborah@bashirian.name",
                            Name = "Tyrique Trantow"
                        },
                        new
                        {
                            Id = 100,
                            Email = "wilford_gutmann@wolfemmerich.uk",
                            Name = "Miss Alycia Morissette"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("CustomerId");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2019, 6, 30, 17, 49, 48, 725, DateTimeKind.Local).AddTicks(7847),
                            CustomerId = 33,
                            Price = 12184.3366m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2019, 5, 1, 17, 49, 48, 726, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 6,
                            Price = 29996.3673m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 5, 31, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 46,
                            Price = 91378.864m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 6, 16, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 11,
                            Price = 47959.3985m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2018, 11, 14, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 77,
                            Price = 39767.3967m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2019, 2, 15, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 16,
                            Price = 32532.3246m
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2018, 10, 29, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 4,
                            Price = 10392.2809m
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2019, 1, 18, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 45,
                            Price = 90041.3613m
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2019, 4, 4, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 54,
                            Price = 59666.1761m
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2019, 6, 19, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 38,
                            Price = 83135.67m
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2018, 11, 11, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 52,
                            Price = 16332.702m
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2018, 12, 17, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 77,
                            Price = 74901.1563m
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2019, 4, 30, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 9,
                            Price = 19820.962m
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2019, 3, 17, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 23,
                            Price = 62284.2616m
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2018, 9, 23, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 29,
                            Price = 7735.414m
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2018, 12, 12, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 26,
                            Price = 89425.2549m
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2018, 10, 23, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 39,
                            Price = 80294.35m
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2019, 2, 19, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 70,
                            Price = 86134.19m
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2019, 3, 7, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 21,
                            Price = 16597.1937m
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2019, 6, 22, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 8,
                            Price = 41518.419m
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2019, 7, 2, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 30,
                            Price = 68601.1118m
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2019, 4, 26, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 1,
                            Price = 12370.2200m
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2019, 3, 13, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 66,
                            Price = 17605.1206m
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2018, 12, 12, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 20,
                            Price = 87051.2806m
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2018, 12, 30, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 52,
                            Price = 44108.1012m
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2019, 2, 15, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 37,
                            Price = 43715.1528m
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2019, 4, 26, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 96,
                            Price = 4850.1471m
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2018, 10, 12, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 17,
                            Price = 49358.3785m
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2019, 6, 6, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 12,
                            Price = 9253.3635m
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2019, 7, 1, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 93,
                            Price = 72015.2692m
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2019, 4, 4, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 26,
                            Price = 59333.3301m
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2019, 2, 19, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 54,
                            Price = 91909.1176m
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2019, 4, 12, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 12,
                            Price = 9756.2751m
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2019, 3, 12, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 8,
                            Price = 856.380m
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2019, 5, 8, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 71,
                            Price = 84112.3582m
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2019, 5, 15, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 48,
                            Price = 73736.448m
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2018, 10, 19, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 94,
                            Price = 2519.2906m
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2018, 12, 8, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 21,
                            Price = 33096.3534m
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2019, 2, 15, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 74,
                            Price = 5182.795m
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2019, 7, 2, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 15,
                            Price = 21491.3586m
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2019, 4, 5, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 50,
                            Price = 37016.3684m
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2019, 1, 25, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 89,
                            Price = 21307.3296m
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2019, 1, 1, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 91,
                            Price = 66650.2048m
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2019, 5, 12, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 4,
                            Price = 58888.1740m
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2018, 12, 17, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 48,
                            Price = 51526.3660m
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2018, 9, 29, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 84,
                            Price = 91225.1027m
                        },
                        new
                        {
                            Id = 47,
                            CreatedDate = new DateTime(2019, 2, 3, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 25,
                            Price = 76426.2968m
                        },
                        new
                        {
                            Id = 48,
                            CreatedDate = new DateTime(2018, 10, 26, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 23,
                            Price = 51151.3442m
                        },
                        new
                        {
                            Id = 49,
                            CreatedDate = new DateTime(2019, 2, 19, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 36,
                            Price = 36057.3318m
                        },
                        new
                        {
                            Id = 50,
                            CreatedDate = new DateTime(2019, 4, 10, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 75,
                            Price = 45266.1952m
                        },
                        new
                        {
                            Id = 51,
                            CreatedDate = new DateTime(2019, 1, 7, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 2,
                            Price = 29296.3101m
                        },
                        new
                        {
                            Id = 52,
                            CreatedDate = new DateTime(2019, 5, 3, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 60,
                            Price = 86055.2181m
                        },
                        new
                        {
                            Id = 53,
                            CreatedDate = new DateTime(2019, 6, 25, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 66,
                            Price = 51575.1299m
                        },
                        new
                        {
                            Id = 54,
                            CreatedDate = new DateTime(2019, 5, 20, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 33,
                            Price = 35702.1287m
                        },
                        new
                        {
                            Id = 55,
                            CreatedDate = new DateTime(2019, 3, 27, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 5,
                            Price = 3681.2439m
                        },
                        new
                        {
                            Id = 56,
                            CreatedDate = new DateTime(2018, 11, 22, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 36,
                            Price = 89447.3575m
                        },
                        new
                        {
                            Id = 57,
                            CreatedDate = new DateTime(2018, 11, 6, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 89,
                            Price = 69407.3293m
                        },
                        new
                        {
                            Id = 58,
                            CreatedDate = new DateTime(2019, 3, 6, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 70,
                            Price = 30292.2688m
                        },
                        new
                        {
                            Id = 59,
                            CreatedDate = new DateTime(2019, 3, 4, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 31,
                            Price = 61235.379m
                        },
                        new
                        {
                            Id = 60,
                            CreatedDate = new DateTime(2019, 4, 11, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 11,
                            Price = 62748.2342m
                        },
                        new
                        {
                            Id = 61,
                            CreatedDate = new DateTime(2019, 5, 5, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 81,
                            Price = 9905.2293m
                        },
                        new
                        {
                            Id = 62,
                            CreatedDate = new DateTime(2018, 10, 4, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 32,
                            Price = 57980.3704m
                        },
                        new
                        {
                            Id = 63,
                            CreatedDate = new DateTime(2019, 2, 24, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 36,
                            Price = 98335.1921m
                        },
                        new
                        {
                            Id = 64,
                            CreatedDate = new DateTime(2019, 4, 17, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 35,
                            Price = 34794.1132m
                        },
                        new
                        {
                            Id = 65,
                            CreatedDate = new DateTime(2018, 12, 2, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 39,
                            Price = 21498.1881m
                        },
                        new
                        {
                            Id = 66,
                            CreatedDate = new DateTime(2019, 4, 5, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 47,
                            Price = 52306.888m
                        },
                        new
                        {
                            Id = 67,
                            CreatedDate = new DateTime(2019, 3, 19, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 45,
                            Price = 74609.2907m
                        },
                        new
                        {
                            Id = 68,
                            CreatedDate = new DateTime(2018, 11, 6, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 89,
                            Price = 60369.2378m
                        },
                        new
                        {
                            Id = 69,
                            CreatedDate = new DateTime(2019, 5, 22, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 79,
                            Price = 6059.2670m
                        },
                        new
                        {
                            Id = 70,
                            CreatedDate = new DateTime(2018, 11, 22, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 73,
                            Price = 30846.1366m
                        },
                        new
                        {
                            Id = 71,
                            CreatedDate = new DateTime(2018, 11, 11, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 9,
                            Price = 15501.1067m
                        },
                        new
                        {
                            Id = 72,
                            CreatedDate = new DateTime(2019, 5, 28, 17, 49, 48, 727, DateTimeKind.Local).AddTicks(7848),
                            CustomerId = 1,
                            Price = 39833.3621m
                        },
                        new
                        {
                            Id = 73,
                            CreatedDate = new DateTime(2018, 9, 22, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 53,
                            Price = 2055.73m
                        },
                        new
                        {
                            Id = 74,
                            CreatedDate = new DateTime(2019, 3, 19, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 46,
                            Price = 56289.3763m
                        },
                        new
                        {
                            Id = 75,
                            CreatedDate = new DateTime(2018, 12, 5, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 20,
                            Price = 43915.3357m
                        },
                        new
                        {
                            Id = 76,
                            CreatedDate = new DateTime(2019, 2, 23, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 22,
                            Price = 24822.1062m
                        },
                        new
                        {
                            Id = 77,
                            CreatedDate = new DateTime(2019, 1, 11, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 40,
                            Price = 20220.3468m
                        },
                        new
                        {
                            Id = 78,
                            CreatedDate = new DateTime(2019, 5, 15, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 15,
                            Price = 38906.2878m
                        },
                        new
                        {
                            Id = 79,
                            CreatedDate = new DateTime(2019, 7, 9, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 9,
                            Price = 19563.3737m
                        },
                        new
                        {
                            Id = 80,
                            CreatedDate = new DateTime(2018, 12, 18, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 95,
                            Price = 56209.141m
                        },
                        new
                        {
                            Id = 81,
                            CreatedDate = new DateTime(2018, 9, 30, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 43,
                            Price = 97696.295m
                        },
                        new
                        {
                            Id = 82,
                            CreatedDate = new DateTime(2019, 3, 19, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 1,
                            Price = 10700.2265m
                        },
                        new
                        {
                            Id = 83,
                            CreatedDate = new DateTime(2019, 3, 6, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 9,
                            Price = 8687.2689m
                        },
                        new
                        {
                            Id = 84,
                            CreatedDate = new DateTime(2018, 11, 13, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 50,
                            Price = 14765.3869m
                        },
                        new
                        {
                            Id = 85,
                            CreatedDate = new DateTime(2019, 3, 11, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 9,
                            Price = 21979.2832m
                        },
                        new
                        {
                            Id = 86,
                            CreatedDate = new DateTime(2019, 6, 14, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 85,
                            Price = 61158.3778m
                        },
                        new
                        {
                            Id = 87,
                            CreatedDate = new DateTime(2019, 3, 9, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 52,
                            Price = 78640.1143m
                        },
                        new
                        {
                            Id = 88,
                            CreatedDate = new DateTime(2019, 6, 6, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 98,
                            Price = 43049.3328m
                        },
                        new
                        {
                            Id = 89,
                            CreatedDate = new DateTime(2019, 6, 29, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 57,
                            Price = 17506.2697m
                        },
                        new
                        {
                            Id = 90,
                            CreatedDate = new DateTime(2019, 3, 4, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 79,
                            Price = 90553.3859m
                        },
                        new
                        {
                            Id = 91,
                            CreatedDate = new DateTime(2019, 3, 27, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 77,
                            Price = 91747.1628m
                        },
                        new
                        {
                            Id = 92,
                            CreatedDate = new DateTime(2019, 2, 25, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 86,
                            Price = 84393.1502m
                        },
                        new
                        {
                            Id = 93,
                            CreatedDate = new DateTime(2019, 4, 18, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 15,
                            Price = 22215.1029m
                        },
                        new
                        {
                            Id = 94,
                            CreatedDate = new DateTime(2019, 5, 20, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 99,
                            Price = 1991.3515m
                        },
                        new
                        {
                            Id = 95,
                            CreatedDate = new DateTime(2018, 11, 15, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 52,
                            Price = 33772.3536m
                        },
                        new
                        {
                            Id = 96,
                            CreatedDate = new DateTime(2019, 3, 19, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 98,
                            Price = 39908.504m
                        },
                        new
                        {
                            Id = 97,
                            CreatedDate = new DateTime(2019, 6, 13, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 29,
                            Price = 10550.1092m
                        },
                        new
                        {
                            Id = 98,
                            CreatedDate = new DateTime(2019, 3, 30, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 60,
                            Price = 36460.324m
                        },
                        new
                        {
                            Id = 99,
                            CreatedDate = new DateTime(2019, 2, 25, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 45,
                            Price = 15988.3327m
                        },
                        new
                        {
                            Id = 100,
                            CreatedDate = new DateTime(2019, 3, 27, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 95,
                            Price = 81843.1392m
                        },
                        new
                        {
                            Id = 101,
                            CreatedDate = new DateTime(2019, 1, 24, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 71,
                            Price = 87083.2382m
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2018, 12, 16, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 26,
                            Price = 72097.2923m
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2018, 12, 17, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 82,
                            Price = 22774.1213m
                        },
                        new
                        {
                            Id = 104,
                            CreatedDate = new DateTime(2018, 12, 16, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 22,
                            Price = 47927.3665m
                        },
                        new
                        {
                            Id = 105,
                            CreatedDate = new DateTime(2019, 2, 15, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 35,
                            Price = 43664.2227m
                        },
                        new
                        {
                            Id = 106,
                            CreatedDate = new DateTime(2019, 2, 22, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 62,
                            Price = 54448.2084m
                        },
                        new
                        {
                            Id = 107,
                            CreatedDate = new DateTime(2019, 4, 29, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 98,
                            Price = 2892.2388m
                        },
                        new
                        {
                            Id = 108,
                            CreatedDate = new DateTime(2018, 12, 25, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 66,
                            Price = 11788.2279m
                        },
                        new
                        {
                            Id = 109,
                            CreatedDate = new DateTime(2019, 3, 3, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 18,
                            Price = 22997.2925m
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2018, 10, 20, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 44,
                            Price = 34426.3318m
                        },
                        new
                        {
                            Id = 111,
                            CreatedDate = new DateTime(2019, 5, 25, 17, 49, 48, 728, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 62,
                            Price = 65244.1074m
                        },
                        new
                        {
                            Id = 112,
                            CreatedDate = new DateTime(2019, 1, 5, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 19,
                            Price = 62954.1342m
                        },
                        new
                        {
                            Id = 113,
                            CreatedDate = new DateTime(2019, 3, 11, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 11,
                            Price = 30911.1941m
                        },
                        new
                        {
                            Id = 114,
                            CreatedDate = new DateTime(2018, 12, 3, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 96,
                            Price = 83923.2053m
                        },
                        new
                        {
                            Id = 115,
                            CreatedDate = new DateTime(2019, 3, 30, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 31,
                            Price = 92129.1397m
                        },
                        new
                        {
                            Id = 116,
                            CreatedDate = new DateTime(2018, 11, 4, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 92,
                            Price = 67226.1372m
                        },
                        new
                        {
                            Id = 117,
                            CreatedDate = new DateTime(2019, 2, 10, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 23,
                            Price = 85602.2229m
                        },
                        new
                        {
                            Id = 118,
                            CreatedDate = new DateTime(2018, 12, 29, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 16,
                            Price = 9401.1287m
                        },
                        new
                        {
                            Id = 119,
                            CreatedDate = new DateTime(2018, 10, 24, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 18,
                            Price = 68617.451m
                        },
                        new
                        {
                            Id = 120,
                            CreatedDate = new DateTime(2019, 1, 1, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 66,
                            Price = 14790.3674m
                        },
                        new
                        {
                            Id = 121,
                            CreatedDate = new DateTime(2018, 10, 14, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 47,
                            Price = 77807.414m
                        },
                        new
                        {
                            Id = 122,
                            CreatedDate = new DateTime(2019, 4, 26, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 58,
                            Price = 44230.3123m
                        },
                        new
                        {
                            Id = 123,
                            CreatedDate = new DateTime(2018, 11, 20, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 24,
                            Price = 33964.3511m
                        },
                        new
                        {
                            Id = 124,
                            CreatedDate = new DateTime(2018, 12, 6, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 97,
                            Price = 9719.2033m
                        },
                        new
                        {
                            Id = 125,
                            CreatedDate = new DateTime(2019, 3, 10, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 71,
                            Price = 15521.3179m
                        },
                        new
                        {
                            Id = 126,
                            CreatedDate = new DateTime(2019, 3, 30, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 72,
                            Price = 85110.1714m
                        },
                        new
                        {
                            Id = 127,
                            CreatedDate = new DateTime(2018, 10, 27, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 41,
                            Price = 48763.3955m
                        },
                        new
                        {
                            Id = 128,
                            CreatedDate = new DateTime(2018, 11, 15, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 14,
                            Price = 69572.2408m
                        },
                        new
                        {
                            Id = 129,
                            CreatedDate = new DateTime(2019, 1, 20, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 89,
                            Price = 96606.1541m
                        },
                        new
                        {
                            Id = 130,
                            CreatedDate = new DateTime(2019, 3, 31, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 21,
                            Price = 42183.2969m
                        },
                        new
                        {
                            Id = 131,
                            CreatedDate = new DateTime(2019, 3, 25, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 57,
                            Price = 46423.3863m
                        },
                        new
                        {
                            Id = 132,
                            CreatedDate = new DateTime(2019, 4, 26, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 3,
                            Price = 99498.348m
                        },
                        new
                        {
                            Id = 133,
                            CreatedDate = new DateTime(2018, 12, 5, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 17,
                            Price = 88462.805m
                        },
                        new
                        {
                            Id = 134,
                            CreatedDate = new DateTime(2018, 12, 31, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 49,
                            Price = 66510.1886m
                        },
                        new
                        {
                            Id = 135,
                            CreatedDate = new DateTime(2019, 6, 7, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 40,
                            Price = 50321.3184m
                        },
                        new
                        {
                            Id = 136,
                            CreatedDate = new DateTime(2019, 4, 27, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 70,
                            Price = 88362.467m
                        },
                        new
                        {
                            Id = 137,
                            CreatedDate = new DateTime(2018, 12, 18, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 2,
                            Price = 58344.1702m
                        },
                        new
                        {
                            Id = 138,
                            CreatedDate = new DateTime(2018, 12, 7, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 23,
                            Price = 5141.2195m
                        },
                        new
                        {
                            Id = 139,
                            CreatedDate = new DateTime(2019, 4, 11, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 53,
                            Price = 82638.3394m
                        },
                        new
                        {
                            Id = 140,
                            CreatedDate = new DateTime(2018, 10, 5, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 1,
                            Price = 99598.1724m
                        },
                        new
                        {
                            Id = 141,
                            CreatedDate = new DateTime(2018, 11, 3, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 61,
                            Price = 38826.1323m
                        },
                        new
                        {
                            Id = 142,
                            CreatedDate = new DateTime(2018, 12, 1, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 70,
                            Price = 35809.506m
                        },
                        new
                        {
                            Id = 143,
                            CreatedDate = new DateTime(2018, 12, 22, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 69,
                            Price = 49828.974m
                        },
                        new
                        {
                            Id = 144,
                            CreatedDate = new DateTime(2019, 5, 28, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 54,
                            Price = 85551.3468m
                        },
                        new
                        {
                            Id = 145,
                            CreatedDate = new DateTime(2019, 4, 22, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 48,
                            Price = 86161.1967m
                        },
                        new
                        {
                            Id = 146,
                            CreatedDate = new DateTime(2018, 12, 8, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 80,
                            Price = 35578.1203m
                        },
                        new
                        {
                            Id = 147,
                            CreatedDate = new DateTime(2019, 6, 29, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 62,
                            Price = 69114.1622m
                        },
                        new
                        {
                            Id = 148,
                            CreatedDate = new DateTime(2019, 2, 1, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 52,
                            Price = 45443.3248m
                        },
                        new
                        {
                            Id = 149,
                            CreatedDate = new DateTime(2018, 11, 7, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 22,
                            Price = 10861.1420m
                        },
                        new
                        {
                            Id = 150,
                            CreatedDate = new DateTime(2018, 9, 29, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 5,
                            Price = 89618.553m
                        },
                        new
                        {
                            Id = 151,
                            CreatedDate = new DateTime(2018, 10, 24, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 63,
                            Price = 21281.2502m
                        },
                        new
                        {
                            Id = 152,
                            CreatedDate = new DateTime(2019, 3, 2, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 80,
                            Price = 504.1436m
                        },
                        new
                        {
                            Id = 153,
                            CreatedDate = new DateTime(2019, 2, 21, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 46,
                            Price = 91115.2936m
                        },
                        new
                        {
                            Id = 154,
                            CreatedDate = new DateTime(2018, 11, 12, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 14,
                            Price = 84506.248m
                        },
                        new
                        {
                            Id = 155,
                            CreatedDate = new DateTime(2019, 2, 28, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 30,
                            Price = 93751.587m
                        },
                        new
                        {
                            Id = 156,
                            CreatedDate = new DateTime(2019, 4, 12, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 3,
                            Price = 77573.469m
                        },
                        new
                        {
                            Id = 157,
                            CreatedDate = new DateTime(2018, 10, 13, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 7,
                            Price = 38933.3962m
                        },
                        new
                        {
                            Id = 158,
                            CreatedDate = new DateTime(2018, 9, 29, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 14,
                            Price = 35400.533m
                        },
                        new
                        {
                            Id = 159,
                            CreatedDate = new DateTime(2019, 4, 20, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 10,
                            Price = 60785.3473m
                        },
                        new
                        {
                            Id = 160,
                            CreatedDate = new DateTime(2019, 6, 1, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 61,
                            Price = 58894.2563m
                        },
                        new
                        {
                            Id = 161,
                            CreatedDate = new DateTime(2019, 1, 13, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 7,
                            Price = 34580.3192m
                        },
                        new
                        {
                            Id = 162,
                            CreatedDate = new DateTime(2019, 3, 1, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 10,
                            Price = 60994.45m
                        },
                        new
                        {
                            Id = 163,
                            CreatedDate = new DateTime(2019, 6, 18, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 80,
                            Price = 44023.2331m
                        },
                        new
                        {
                            Id = 164,
                            CreatedDate = new DateTime(2019, 6, 15, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 99,
                            Price = 42582.711m
                        },
                        new
                        {
                            Id = 165,
                            CreatedDate = new DateTime(2019, 2, 7, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 30,
                            Price = 97114.957m
                        },
                        new
                        {
                            Id = 166,
                            CreatedDate = new DateTime(2018, 10, 16, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 37,
                            Price = 44020.1885m
                        },
                        new
                        {
                            Id = 167,
                            CreatedDate = new DateTime(2018, 10, 18, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 36,
                            Price = 95251.3430m
                        },
                        new
                        {
                            Id = 168,
                            CreatedDate = new DateTime(2018, 11, 26, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 45,
                            Price = 21835.3050m
                        },
                        new
                        {
                            Id = 169,
                            CreatedDate = new DateTime(2019, 1, 8, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 42,
                            Price = 32592.3995m
                        },
                        new
                        {
                            Id = 170,
                            CreatedDate = new DateTime(2019, 6, 16, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 96,
                            Price = 21534.3056m
                        },
                        new
                        {
                            Id = 171,
                            CreatedDate = new DateTime(2019, 5, 30, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 34,
                            Price = 39866.3173m
                        },
                        new
                        {
                            Id = 172,
                            CreatedDate = new DateTime(2018, 11, 22, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 82,
                            Price = 92956.2858m
                        },
                        new
                        {
                            Id = 173,
                            CreatedDate = new DateTime(2019, 4, 2, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 5,
                            Price = 71612.953m
                        },
                        new
                        {
                            Id = 174,
                            CreatedDate = new DateTime(2018, 10, 7, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 97,
                            Price = 91149.2802m
                        },
                        new
                        {
                            Id = 175,
                            CreatedDate = new DateTime(2018, 11, 15, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 65,
                            Price = 5161.1284m
                        },
                        new
                        {
                            Id = 176,
                            CreatedDate = new DateTime(2019, 5, 26, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 86,
                            Price = 20425.960m
                        },
                        new
                        {
                            Id = 177,
                            CreatedDate = new DateTime(2019, 1, 21, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 46,
                            Price = 76610.1021m
                        },
                        new
                        {
                            Id = 178,
                            CreatedDate = new DateTime(2019, 1, 6, 17, 49, 48, 729, DateTimeKind.Local).AddTicks(7849),
                            CustomerId = 50,
                            Price = 79249.1659m
                        },
                        new
                        {
                            Id = 179,
                            CreatedDate = new DateTime(2019, 2, 26, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 68,
                            Price = 1567.3974m
                        },
                        new
                        {
                            Id = 180,
                            CreatedDate = new DateTime(2018, 12, 19, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 24,
                            Price = 91893.1313m
                        },
                        new
                        {
                            Id = 181,
                            CreatedDate = new DateTime(2019, 4, 13, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 65,
                            Price = 30829.2668m
                        },
                        new
                        {
                            Id = 182,
                            CreatedDate = new DateTime(2019, 4, 8, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 53,
                            Price = 9088.2792m
                        },
                        new
                        {
                            Id = 183,
                            CreatedDate = new DateTime(2018, 9, 25, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 15,
                            Price = 70667.1217m
                        },
                        new
                        {
                            Id = 184,
                            CreatedDate = new DateTime(2019, 1, 8, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 80,
                            Price = 16481.2126m
                        },
                        new
                        {
                            Id = 185,
                            CreatedDate = new DateTime(2019, 2, 22, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 38,
                            Price = 77228.2365m
                        },
                        new
                        {
                            Id = 186,
                            CreatedDate = new DateTime(2018, 10, 10, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 52,
                            Price = 80732.2435m
                        },
                        new
                        {
                            Id = 187,
                            CreatedDate = new DateTime(2018, 11, 21, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 70,
                            Price = 65313.3299m
                        },
                        new
                        {
                            Id = 188,
                            CreatedDate = new DateTime(2018, 10, 11, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 39,
                            Price = 24221.2209m
                        },
                        new
                        {
                            Id = 189,
                            CreatedDate = new DateTime(2019, 5, 15, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 48,
                            Price = 86843.3580m
                        },
                        new
                        {
                            Id = 190,
                            CreatedDate = new DateTime(2018, 11, 12, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 84,
                            Price = 29520.807m
                        },
                        new
                        {
                            Id = 191,
                            CreatedDate = new DateTime(2019, 4, 1, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 11,
                            Price = 67127.2901m
                        },
                        new
                        {
                            Id = 192,
                            CreatedDate = new DateTime(2018, 12, 7, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 98,
                            Price = 12621.2599m
                        },
                        new
                        {
                            Id = 193,
                            CreatedDate = new DateTime(2019, 3, 2, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 15,
                            Price = 3504.800m
                        },
                        new
                        {
                            Id = 194,
                            CreatedDate = new DateTime(2019, 5, 23, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 75,
                            Price = 70521.2788m
                        },
                        new
                        {
                            Id = 195,
                            CreatedDate = new DateTime(2019, 4, 4, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 84,
                            Price = 6516.3214m
                        },
                        new
                        {
                            Id = 196,
                            CreatedDate = new DateTime(2019, 3, 17, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 38,
                            Price = 74696.1328m
                        },
                        new
                        {
                            Id = 197,
                            CreatedDate = new DateTime(2018, 12, 27, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 28,
                            Price = 7997.3547m
                        },
                        new
                        {
                            Id = 198,
                            CreatedDate = new DateTime(2019, 1, 19, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 12,
                            Price = 45585.2925m
                        },
                        new
                        {
                            Id = 199,
                            CreatedDate = new DateTime(2019, 1, 5, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 94,
                            Price = 70258.925m
                        },
                        new
                        {
                            Id = 200,
                            CreatedDate = new DateTime(2019, 3, 25, 17, 49, 48, 730, DateTimeKind.Local).AddTicks(7850),
                            CustomerId = 96,
                            Price = 803.1646m
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK_Orders_Customers_CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
