// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Persistance;

namespace Shop.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20190711222454_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Shop.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "syble_gutmann@gleason.com",
                            Name = "Daphne Erdman II"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bonita@labadie.uk",
                            Name = "Mr. Maribel Raynor"
                        },
                        new
                        {
                            Id = 3,
                            Email = "catalina_kerluke@bechtelar.co.uk",
                            Name = "Florine Brekke"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ronny@pagac.biz",
                            Name = "Hailee Zemlak"
                        },
                        new
                        {
                            Id = 5,
                            Email = "roselyn@pouros.name",
                            Name = "Kristy Wintheiser"
                        },
                        new
                        {
                            Id = 6,
                            Email = "roxanne@kris.com",
                            Name = "Marlin Spencer PhD"
                        },
                        new
                        {
                            Id = 7,
                            Email = "dominique@halvorson.info",
                            Name = "Ashleigh Tremblay"
                        },
                        new
                        {
                            Id = 8,
                            Email = "judge_wilderman@nader.com",
                            Name = "Khalil Rippin"
                        },
                        new
                        {
                            Id = 9,
                            Email = "rebecca@fritsch.info",
                            Name = "Sidney Frami V"
                        },
                        new
                        {
                            Id = 10,
                            Email = "bulah@blockhintz.name",
                            Name = "Amos Kunde"
                        },
                        new
                        {
                            Id = 11,
                            Email = "erna@yundt.com",
                            Name = "Boyd Hane Sr."
                        },
                        new
                        {
                            Id = 12,
                            Email = "abraham_prosacco@kunzegreen.name",
                            Name = "Herminio Nader"
                        },
                        new
                        {
                            Id = 13,
                            Email = "jayce@schiller.co.uk",
                            Name = "Leone Ratke"
                        },
                        new
                        {
                            Id = 14,
                            Email = "anahi_christiansen@schmittchamplin.co.uk",
                            Name = "Taya Schoen"
                        },
                        new
                        {
                            Id = 15,
                            Email = "adell@mcglynnbergnaum.us",
                            Name = "Gerard Beahan"
                        },
                        new
                        {
                            Id = 16,
                            Email = "chet.rau@schneiderstanton.biz",
                            Name = "Jazmin Terry"
                        },
                        new
                        {
                            Id = 17,
                            Email = "liliana_stark@powlowskifisher.info",
                            Name = "Wilfred Raynor MD"
                        },
                        new
                        {
                            Id = 18,
                            Email = "kellie@greenbeer.uk",
                            Name = "Edwardo Langosh"
                        },
                        new
                        {
                            Id = 19,
                            Email = "alison@schinner.info",
                            Name = "Jefferey Emmerich"
                        },
                        new
                        {
                            Id = 20,
                            Email = "quinn@oreillyhilll.com",
                            Name = "Madisyn Wilkinson"
                        },
                        new
                        {
                            Id = 21,
                            Email = "lionel_pouros@jakubowskiorn.com",
                            Name = "Nyah Rippin"
                        },
                        new
                        {
                            Id = 22,
                            Email = "jan@kuphalmonahan.info",
                            Name = "Onie Langworth DDS"
                        },
                        new
                        {
                            Id = 23,
                            Email = "violet_smitham@kris.com",
                            Name = "Ruthe Grady"
                        },
                        new
                        {
                            Id = 24,
                            Email = "benny_mcdermott@lemkequigley.com",
                            Name = "Stefan Greenfelder"
                        },
                        new
                        {
                            Id = 25,
                            Email = "casimir@harvey.com",
                            Name = "Mason Wilkinson"
                        },
                        new
                        {
                            Id = 26,
                            Email = "jacinto.olson@steuber.name",
                            Name = "Hassan Tillman"
                        },
                        new
                        {
                            Id = 27,
                            Email = "lewis@larsonhessel.biz",
                            Name = "Madalyn Willms"
                        },
                        new
                        {
                            Id = 28,
                            Email = "monique_ullrich@kessler.biz",
                            Name = "Darrel Goyette"
                        },
                        new
                        {
                            Id = 29,
                            Email = "agustin.franecki@douglas.ca",
                            Name = "Alexis Johnson III"
                        },
                        new
                        {
                            Id = 30,
                            Email = "monty_lebsack@reilly.us",
                            Name = "Ozella Kuhlman"
                        },
                        new
                        {
                            Id = 31,
                            Email = "jettie@ohara.com",
                            Name = "Brett Boehm"
                        },
                        new
                        {
                            Id = 32,
                            Email = "jules@millerbruen.us",
                            Name = "Ora Moen"
                        },
                        new
                        {
                            Id = 33,
                            Email = "ezra.feil@dare.name",
                            Name = "Hertha Hodkiewicz"
                        },
                        new
                        {
                            Id = 34,
                            Email = "tamara@watsica.name",
                            Name = "Dr. Cecilia Orn"
                        },
                        new
                        {
                            Id = 35,
                            Email = "adele_kessler@damore.ca",
                            Name = "Tod Hayes"
                        },
                        new
                        {
                            Id = 36,
                            Email = "raoul_bernhard@ernser.biz",
                            Name = "Maurine Wehner"
                        },
                        new
                        {
                            Id = 37,
                            Email = "lester@oreillyvandervort.ca",
                            Name = "Zita Mitchell DVM"
                        },
                        new
                        {
                            Id = 38,
                            Email = "ezra@hermann.name",
                            Name = "Shaina Kilback"
                        },
                        new
                        {
                            Id = 39,
                            Email = "jaren@gulgowski.info",
                            Name = "Zack King"
                        },
                        new
                        {
                            Id = 40,
                            Email = "deangelo@abernathy.name",
                            Name = "Judge Aufderhar"
                        },
                        new
                        {
                            Id = 41,
                            Email = "luisa@hoeger.uk",
                            Name = "Lamar Morar"
                        },
                        new
                        {
                            Id = 42,
                            Email = "wanda@powlowski.com",
                            Name = "Angie McGlynn"
                        },
                        new
                        {
                            Id = 43,
                            Email = "macey_greenholt@durgandurgan.us",
                            Name = "Novella Langworth IV"
                        },
                        new
                        {
                            Id = 44,
                            Email = "lydia@schneider.biz",
                            Name = "Haley Kling"
                        },
                        new
                        {
                            Id = 45,
                            Email = "marco.beahan@littelkemmer.uk",
                            Name = "Madison Morar"
                        },
                        new
                        {
                            Id = 46,
                            Email = "beth@zemlakward.co.uk",
                            Name = "Murl Moore"
                        },
                        new
                        {
                            Id = 47,
                            Email = "jake@waters.us",
                            Name = "Crystal Feeney"
                        },
                        new
                        {
                            Id = 48,
                            Email = "kareem@stokes.name",
                            Name = "Theodora Wilderman"
                        },
                        new
                        {
                            Id = 49,
                            Email = "olen_hane@sporer.us",
                            Name = "Delfina Cummings"
                        },
                        new
                        {
                            Id = 50,
                            Email = "maggie@langworthhayes.uk",
                            Name = "Logan Adams"
                        },
                        new
                        {
                            Id = 51,
                            Email = "kaley.dickinson@eichmann.co.uk",
                            Name = "Jade Bins V"
                        },
                        new
                        {
                            Id = 52,
                            Email = "delbert@kutch.us",
                            Name = "Dr. Ezequiel Lueilwitz"
                        },
                        new
                        {
                            Id = 53,
                            Email = "alexandrea@farrellkerluke.us",
                            Name = "Maryam Brown"
                        },
                        new
                        {
                            Id = 54,
                            Email = "autumn.gaylord@bosco.co.uk",
                            Name = "Jeffery O'Kon"
                        },
                        new
                        {
                            Id = 55,
                            Email = "catalina_braun@glover.co.uk",
                            Name = "Mrs. Raegan Schmeler"
                        },
                        new
                        {
                            Id = 56,
                            Email = "connor@kuhn.info",
                            Name = "Elisha Trantow III"
                        },
                        new
                        {
                            Id = 57,
                            Email = "jasper@watsica.co.uk",
                            Name = "Haley Bechtelar"
                        },
                        new
                        {
                            Id = 58,
                            Email = "elvera_stracke@casperkozey.co.uk",
                            Name = "Cicero Koepp"
                        },
                        new
                        {
                            Id = 59,
                            Email = "percy.stehr@torphy.biz",
                            Name = "Jessyca Lesch"
                        },
                        new
                        {
                            Id = 60,
                            Email = "candelario@lynch.info",
                            Name = "Isadore Zieme"
                        },
                        new
                        {
                            Id = 61,
                            Email = "yesenia@anderson.us",
                            Name = "Carroll Wisozk"
                        },
                        new
                        {
                            Id = 62,
                            Email = "albertha@kertzmann.us",
                            Name = "Frieda Gusikowski DDS"
                        },
                        new
                        {
                            Id = 63,
                            Email = "santiago@torphy.ca",
                            Name = "Carlos Heaney"
                        },
                        new
                        {
                            Id = 64,
                            Email = "noemy.legros@mrazwilliamson.com",
                            Name = "Aiyana Kunde"
                        },
                        new
                        {
                            Id = 65,
                            Email = "destinee@pfannerstill.us",
                            Name = "Lukas Little"
                        },
                        new
                        {
                            Id = 66,
                            Email = "gregory@abshiremuller.info",
                            Name = "Margret Braun"
                        },
                        new
                        {
                            Id = 67,
                            Email = "lambert.swaniawski@zulaufblock.uk",
                            Name = "Dr. Bradly Beer"
                        },
                        new
                        {
                            Id = 68,
                            Email = "laurence@monahan.co.uk",
                            Name = "Reece Kunde"
                        },
                        new
                        {
                            Id = 69,
                            Email = "ernestina.von@hammes.us",
                            Name = "Ernie Funk"
                        },
                        new
                        {
                            Id = 70,
                            Email = "alysson@schmeler.uk",
                            Name = "Kelli Kuphal"
                        },
                        new
                        {
                            Id = 71,
                            Email = "pablo_mohr@schoen.uk",
                            Name = "Marshall Lubowitz"
                        },
                        new
                        {
                            Id = 72,
                            Email = "sarina@langworth.us",
                            Name = "Nannie Gleichner"
                        },
                        new
                        {
                            Id = 73,
                            Email = "kyra_hamill@blandatrantow.uk",
                            Name = "Desiree Robel"
                        },
                        new
                        {
                            Id = 74,
                            Email = "ludie@balistreri.us",
                            Name = "Lue Pollich"
                        },
                        new
                        {
                            Id = 75,
                            Email = "cecil_fay@darekassulke.us",
                            Name = "Jordan West"
                        },
                        new
                        {
                            Id = 76,
                            Email = "ubaldo@dach.com",
                            Name = "Vernice Pagac"
                        },
                        new
                        {
                            Id = 77,
                            Email = "amara@stamm.name",
                            Name = "Tate Walker DDS"
                        },
                        new
                        {
                            Id = 78,
                            Email = "percy_jewess@bogisich.name",
                            Name = "Willie Romaguera"
                        },
                        new
                        {
                            Id = 79,
                            Email = "adrian.powlowski@steuber.co.uk",
                            Name = "Bennie Ebert"
                        },
                        new
                        {
                            Id = 80,
                            Email = "arianna@hilpert.com",
                            Name = "Layne Bahringer"
                        },
                        new
                        {
                            Id = 81,
                            Email = "idella.spencer@robel.com",
                            Name = "Caden Wolf"
                        },
                        new
                        {
                            Id = 82,
                            Email = "alford@corwinfarrell.uk",
                            Name = "Raymond Lehner"
                        },
                        new
                        {
                            Id = 83,
                            Email = "bryana_rutherford@hayesrau.name",
                            Name = "Leora Walker"
                        },
                        new
                        {
                            Id = 84,
                            Email = "melyssa@schaefer.co.uk",
                            Name = "Ebony Schinner"
                        },
                        new
                        {
                            Id = 85,
                            Email = "candelario.mohr@rice.info",
                            Name = "Dr. Darrin Leannon"
                        },
                        new
                        {
                            Id = 86,
                            Email = "winston@hodkiewicz.uk",
                            Name = "Alena Lemke"
                        },
                        new
                        {
                            Id = 87,
                            Email = "casimir@konopelski.name",
                            Name = "Mose Muller"
                        },
                        new
                        {
                            Id = 88,
                            Email = "estrella@jacobsherzog.name",
                            Name = "Lenny Cassin"
                        },
                        new
                        {
                            Id = 89,
                            Email = "wendell.buckridge@runtelegros.biz",
                            Name = "Cassidy Orn"
                        },
                        new
                        {
                            Id = 90,
                            Email = "karolann_tremblay@yundt.com",
                            Name = "Ms. Casimer Barton"
                        },
                        new
                        {
                            Id = 91,
                            Email = "mabelle@pouroscrona.biz",
                            Name = "Patsy Tromp"
                        },
                        new
                        {
                            Id = 92,
                            Email = "ned_roob@feeneyosinski.us",
                            Name = "Elsa Schulist"
                        },
                        new
                        {
                            Id = 93,
                            Email = "imani@miller.info",
                            Name = "Alisha Spencer"
                        },
                        new
                        {
                            Id = 94,
                            Email = "alejandra@schultz.uk",
                            Name = "Brandyn Abbott"
                        },
                        new
                        {
                            Id = 95,
                            Email = "jasmin@heller.name",
                            Name = "Archibald Hintz"
                        },
                        new
                        {
                            Id = 96,
                            Email = "emerson_douglas@wiegand.ca",
                            Name = "Nathen Lehner"
                        },
                        new
                        {
                            Id = 97,
                            Email = "jessyca@keeling.co.uk",
                            Name = "Stone Goyette"
                        },
                        new
                        {
                            Id = 98,
                            Email = "marjolaine.mann@hettinger.co.uk",
                            Name = "Marilyne Conroy"
                        },
                        new
                        {
                            Id = 99,
                            Email = "watson@pfannerstill.info",
                            Name = "Magdalena Batz"
                        },
                        new
                        {
                            Id = 100,
                            Email = "susan.damore@stokes.info",
                            Name = "Samir Leffler"
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("CustomerId");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2018, 10, 31, 1, 24, 53, 678, DateTimeKind.Local).AddTicks(7965),
                            CustomerId = 1,
                            Price = 51693.2887m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2018, 12, 27, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 61,
                            Price = 68991.2517m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2019, 7, 8, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 94,
                            Price = 36034.1176m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2019, 7, 9, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 50,
                            Price = 22541.3151m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2018, 10, 4, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 63,
                            Price = 2452.3914m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2018, 10, 20, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 54,
                            Price = 71630.766m
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2019, 3, 5, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 46,
                            Price = 46894.3299m
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2019, 3, 9, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 68,
                            Price = 61871.1466m
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2019, 5, 17, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 50,
                            Price = 30290.735m
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2019, 4, 6, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 61,
                            Price = 54274.945m
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2018, 10, 11, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 40,
                            Price = 13125.1940m
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2018, 12, 26, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 47,
                            Price = 38230.226m
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2018, 12, 12, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 85,
                            Price = 61013.2772m
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2018, 11, 27, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 10,
                            Price = 45785.154m
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2019, 3, 27, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 62,
                            Price = 82493.3545m
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2019, 5, 26, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 36,
                            Price = 85133.623m
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2018, 11, 14, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 2,
                            Price = 33585.3307m
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2019, 1, 14, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 55,
                            Price = 88800.1637m
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2019, 7, 7, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 12,
                            Price = 30075.798m
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2019, 3, 20, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 13,
                            Price = 79412.1921m
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2019, 2, 12, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 12,
                            Price = 98102.3681m
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2018, 10, 12, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 28,
                            Price = 1216.760m
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2019, 3, 11, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 31,
                            Price = 29499.2779m
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2019, 5, 7, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 91,
                            Price = 75747.956m
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2019, 4, 19, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 41,
                            Price = 96605.3354m
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2019, 2, 21, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 18,
                            Price = 63655.621m
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2018, 10, 18, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 100,
                            Price = 62425.1183m
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2018, 10, 28, 1, 24, 53, 680, DateTimeKind.Local).AddTicks(7966),
                            CustomerId = 20,
                            Price = 57048.126m
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2019, 1, 27, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 15,
                            Price = 33957.2533m
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2019, 3, 9, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 4,
                            Price = 1919.2669m
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2019, 4, 26, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 55,
                            Price = 83631.747m
                        },
                        new
                        {
                            Id = 32,
                            CreatedDate = new DateTime(2019, 4, 2, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 82,
                            Price = 96282.552m
                        },
                        new
                        {
                            Id = 33,
                            CreatedDate = new DateTime(2018, 12, 20, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 74,
                            Price = 12729.2241m
                        },
                        new
                        {
                            Id = 34,
                            CreatedDate = new DateTime(2019, 3, 20, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 42,
                            Price = 85584.2568m
                        },
                        new
                        {
                            Id = 35,
                            CreatedDate = new DateTime(2019, 1, 30, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 33,
                            Price = 93676.837m
                        },
                        new
                        {
                            Id = 36,
                            CreatedDate = new DateTime(2019, 4, 5, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 54,
                            Price = 6598.412m
                        },
                        new
                        {
                            Id = 37,
                            CreatedDate = new DateTime(2019, 1, 4, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 46,
                            Price = 38984.249m
                        },
                        new
                        {
                            Id = 38,
                            CreatedDate = new DateTime(2018, 10, 28, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 84,
                            Price = 25537.843m
                        },
                        new
                        {
                            Id = 39,
                            CreatedDate = new DateTime(2018, 12, 21, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 92,
                            Price = 47305.768m
                        },
                        new
                        {
                            Id = 40,
                            CreatedDate = new DateTime(2019, 5, 14, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 37,
                            Price = 76156.3660m
                        },
                        new
                        {
                            Id = 41,
                            CreatedDate = new DateTime(2018, 11, 14, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 27,
                            Price = 93552.875m
                        },
                        new
                        {
                            Id = 42,
                            CreatedDate = new DateTime(2019, 5, 8, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 43,
                            Price = 7260.3944m
                        },
                        new
                        {
                            Id = 43,
                            CreatedDate = new DateTime(2018, 11, 10, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 5,
                            Price = 24986.2783m
                        },
                        new
                        {
                            Id = 44,
                            CreatedDate = new DateTime(2019, 4, 19, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 17,
                            Price = 53162.159m
                        },
                        new
                        {
                            Id = 45,
                            CreatedDate = new DateTime(2018, 9, 20, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 74,
                            Price = 25634.3425m
                        },
                        new
                        {
                            Id = 46,
                            CreatedDate = new DateTime(2019, 3, 22, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 93,
                            Price = 6983.2669m
                        },
                        new
                        {
                            Id = 47,
                            CreatedDate = new DateTime(2019, 2, 11, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 37,
                            Price = 18050.507m
                        },
                        new
                        {
                            Id = 48,
                            CreatedDate = new DateTime(2019, 5, 14, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 78,
                            Price = 64398.3177m
                        },
                        new
                        {
                            Id = 49,
                            CreatedDate = new DateTime(2018, 10, 12, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 82,
                            Price = 95763.3496m
                        },
                        new
                        {
                            Id = 50,
                            CreatedDate = new DateTime(2018, 12, 25, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 87,
                            Price = 6285.2938m
                        },
                        new
                        {
                            Id = 51,
                            CreatedDate = new DateTime(2018, 10, 19, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 12,
                            Price = 83906.461m
                        },
                        new
                        {
                            Id = 52,
                            CreatedDate = new DateTime(2019, 3, 25, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 40,
                            Price = 30233.3027m
                        },
                        new
                        {
                            Id = 53,
                            CreatedDate = new DateTime(2018, 12, 18, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 97,
                            Price = 77269.2133m
                        },
                        new
                        {
                            Id = 54,
                            CreatedDate = new DateTime(2019, 1, 23, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 60,
                            Price = 76561.2247m
                        },
                        new
                        {
                            Id = 55,
                            CreatedDate = new DateTime(2018, 10, 4, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 13,
                            Price = 4050.1438m
                        },
                        new
                        {
                            Id = 56,
                            CreatedDate = new DateTime(2018, 10, 5, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 3,
                            Price = 55864.589m
                        },
                        new
                        {
                            Id = 57,
                            CreatedDate = new DateTime(2019, 4, 29, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 63,
                            Price = 87177.415m
                        },
                        new
                        {
                            Id = 58,
                            CreatedDate = new DateTime(2018, 11, 16, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 2,
                            Price = 73178.2470m
                        },
                        new
                        {
                            Id = 59,
                            CreatedDate = new DateTime(2018, 12, 5, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 13,
                            Price = 11414.3906m
                        },
                        new
                        {
                            Id = 60,
                            CreatedDate = new DateTime(2019, 2, 22, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 7,
                            Price = 88821.1725m
                        },
                        new
                        {
                            Id = 61,
                            CreatedDate = new DateTime(2018, 9, 17, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 95,
                            Price = 2879.3263m
                        },
                        new
                        {
                            Id = 62,
                            CreatedDate = new DateTime(2019, 1, 22, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 71,
                            Price = 38576.321m
                        },
                        new
                        {
                            Id = 63,
                            CreatedDate = new DateTime(2018, 10, 26, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 96,
                            Price = 13946.1594m
                        },
                        new
                        {
                            Id = 64,
                            CreatedDate = new DateTime(2018, 11, 23, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 62,
                            Price = 92268.1052m
                        },
                        new
                        {
                            Id = 65,
                            CreatedDate = new DateTime(2019, 6, 21, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 43,
                            Price = 41842.1844m
                        },
                        new
                        {
                            Id = 66,
                            CreatedDate = new DateTime(2019, 1, 19, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 74,
                            Price = 25312.2395m
                        },
                        new
                        {
                            Id = 67,
                            CreatedDate = new DateTime(2018, 9, 22, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 63,
                            Price = 12929.107m
                        },
                        new
                        {
                            Id = 68,
                            CreatedDate = new DateTime(2019, 4, 4, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 66,
                            Price = 7614.3280m
                        },
                        new
                        {
                            Id = 69,
                            CreatedDate = new DateTime(2019, 5, 9, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 41,
                            Price = 91640.1263m
                        },
                        new
                        {
                            Id = 70,
                            CreatedDate = new DateTime(2019, 7, 2, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 73,
                            Price = 21353.2866m
                        },
                        new
                        {
                            Id = 71,
                            CreatedDate = new DateTime(2019, 2, 4, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 49,
                            Price = 93022.3879m
                        },
                        new
                        {
                            Id = 72,
                            CreatedDate = new DateTime(2018, 10, 2, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 28,
                            Price = 99944.3586m
                        },
                        new
                        {
                            Id = 73,
                            CreatedDate = new DateTime(2018, 10, 10, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 71,
                            Price = 29763.3689m
                        },
                        new
                        {
                            Id = 74,
                            CreatedDate = new DateTime(2018, 11, 8, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 84,
                            Price = 79562.306m
                        },
                        new
                        {
                            Id = 75,
                            CreatedDate = new DateTime(2019, 1, 19, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 20,
                            Price = 39500.105m
                        },
                        new
                        {
                            Id = 76,
                            CreatedDate = new DateTime(2019, 4, 18, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 80,
                            Price = 68013.3924m
                        },
                        new
                        {
                            Id = 77,
                            CreatedDate = new DateTime(2019, 6, 13, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 95,
                            Price = 98583.2525m
                        },
                        new
                        {
                            Id = 78,
                            CreatedDate = new DateTime(2019, 6, 3, 1, 24, 53, 681, DateTimeKind.Local).AddTicks(7967),
                            CustomerId = 2,
                            Price = 70578.92m
                        },
                        new
                        {
                            Id = 79,
                            CreatedDate = new DateTime(2019, 5, 3, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 19,
                            Price = 72959.887m
                        },
                        new
                        {
                            Id = 80,
                            CreatedDate = new DateTime(2018, 10, 14, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 32,
                            Price = 61729.1496m
                        },
                        new
                        {
                            Id = 81,
                            CreatedDate = new DateTime(2018, 9, 25, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 84,
                            Price = 61065.2010m
                        },
                        new
                        {
                            Id = 82,
                            CreatedDate = new DateTime(2018, 12, 16, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 91,
                            Price = 14340.2317m
                        },
                        new
                        {
                            Id = 83,
                            CreatedDate = new DateTime(2018, 10, 2, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 89,
                            Price = 10658.3838m
                        },
                        new
                        {
                            Id = 84,
                            CreatedDate = new DateTime(2018, 10, 18, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 44,
                            Price = 1813.3379m
                        },
                        new
                        {
                            Id = 85,
                            CreatedDate = new DateTime(2019, 2, 3, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 8,
                            Price = 2782.3646m
                        },
                        new
                        {
                            Id = 86,
                            CreatedDate = new DateTime(2018, 10, 17, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 84,
                            Price = 70114.3193m
                        },
                        new
                        {
                            Id = 87,
                            CreatedDate = new DateTime(2018, 12, 30, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 11,
                            Price = 76304.686m
                        },
                        new
                        {
                            Id = 88,
                            CreatedDate = new DateTime(2019, 6, 7, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 94,
                            Price = 50119.236m
                        },
                        new
                        {
                            Id = 89,
                            CreatedDate = new DateTime(2019, 3, 1, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 82,
                            Price = 81642.1956m
                        },
                        new
                        {
                            Id = 90,
                            CreatedDate = new DateTime(2019, 1, 10, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 15,
                            Price = 78283.868m
                        },
                        new
                        {
                            Id = 91,
                            CreatedDate = new DateTime(2019, 6, 18, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 77,
                            Price = 60294.3384m
                        },
                        new
                        {
                            Id = 92,
                            CreatedDate = new DateTime(2018, 11, 4, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 34,
                            Price = 86802.1568m
                        },
                        new
                        {
                            Id = 93,
                            CreatedDate = new DateTime(2019, 6, 4, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 15,
                            Price = 78094.1088m
                        },
                        new
                        {
                            Id = 94,
                            CreatedDate = new DateTime(2019, 5, 10, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 70,
                            Price = 61313.1991m
                        },
                        new
                        {
                            Id = 95,
                            CreatedDate = new DateTime(2019, 5, 13, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 87,
                            Price = 32119.211m
                        },
                        new
                        {
                            Id = 96,
                            CreatedDate = new DateTime(2019, 5, 4, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 41,
                            Price = 9056.2778m
                        },
                        new
                        {
                            Id = 97,
                            CreatedDate = new DateTime(2019, 3, 28, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 33,
                            Price = 69852.3357m
                        },
                        new
                        {
                            Id = 98,
                            CreatedDate = new DateTime(2019, 6, 28, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 14,
                            Price = 10584.1710m
                        },
                        new
                        {
                            Id = 99,
                            CreatedDate = new DateTime(2019, 5, 9, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 10,
                            Price = 82636.1680m
                        },
                        new
                        {
                            Id = 100,
                            CreatedDate = new DateTime(2019, 3, 12, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 79,
                            Price = 79003.1351m
                        },
                        new
                        {
                            Id = 101,
                            CreatedDate = new DateTime(2019, 3, 16, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 49,
                            Price = 90426.3803m
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2019, 5, 21, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 61,
                            Price = 4870.1933m
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2018, 9, 21, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 10,
                            Price = 32525.3527m
                        },
                        new
                        {
                            Id = 104,
                            CreatedDate = new DateTime(2018, 10, 21, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 91,
                            Price = 21799.3256m
                        },
                        new
                        {
                            Id = 105,
                            CreatedDate = new DateTime(2019, 5, 31, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 61,
                            Price = 13021.2587m
                        },
                        new
                        {
                            Id = 106,
                            CreatedDate = new DateTime(2018, 10, 2, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 54,
                            Price = 20675.961m
                        },
                        new
                        {
                            Id = 107,
                            CreatedDate = new DateTime(2019, 3, 1, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 58,
                            Price = 43900.1600m
                        },
                        new
                        {
                            Id = 108,
                            CreatedDate = new DateTime(2018, 10, 25, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 17,
                            Price = 77116.3057m
                        },
                        new
                        {
                            Id = 109,
                            CreatedDate = new DateTime(2018, 9, 20, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 21,
                            Price = 63453.3005m
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2018, 12, 28, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 12,
                            Price = 79844.3337m
                        },
                        new
                        {
                            Id = 111,
                            CreatedDate = new DateTime(2018, 11, 3, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 29,
                            Price = 34652.2081m
                        },
                        new
                        {
                            Id = 112,
                            CreatedDate = new DateTime(2019, 6, 6, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 12,
                            Price = 52358.3899m
                        },
                        new
                        {
                            Id = 113,
                            CreatedDate = new DateTime(2019, 1, 24, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 48,
                            Price = 82105.26m
                        },
                        new
                        {
                            Id = 114,
                            CreatedDate = new DateTime(2018, 11, 7, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 59,
                            Price = 9977.3694m
                        },
                        new
                        {
                            Id = 115,
                            CreatedDate = new DateTime(2019, 2, 12, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 9,
                            Price = 6587.294m
                        },
                        new
                        {
                            Id = 116,
                            CreatedDate = new DateTime(2019, 4, 13, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 51,
                            Price = 23262.1585m
                        },
                        new
                        {
                            Id = 117,
                            CreatedDate = new DateTime(2019, 1, 5, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 37,
                            Price = 69909.1779m
                        },
                        new
                        {
                            Id = 118,
                            CreatedDate = new DateTime(2018, 9, 23, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 90,
                            Price = 31277.2608m
                        },
                        new
                        {
                            Id = 119,
                            CreatedDate = new DateTime(2019, 5, 1, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 72,
                            Price = 79745.1538m
                        },
                        new
                        {
                            Id = 120,
                            CreatedDate = new DateTime(2019, 5, 20, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 33,
                            Price = 6674.3596m
                        },
                        new
                        {
                            Id = 121,
                            CreatedDate = new DateTime(2018, 10, 6, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 17,
                            Price = 5409.3196m
                        },
                        new
                        {
                            Id = 122,
                            CreatedDate = new DateTime(2018, 10, 26, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 22,
                            Price = 36764.2697m
                        },
                        new
                        {
                            Id = 123,
                            CreatedDate = new DateTime(2018, 10, 19, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 33,
                            Price = 84620.3400m
                        },
                        new
                        {
                            Id = 124,
                            CreatedDate = new DateTime(2019, 1, 12, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 53,
                            Price = 25555.1193m
                        },
                        new
                        {
                            Id = 125,
                            CreatedDate = new DateTime(2018, 9, 30, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 2,
                            Price = 6824.1365m
                        },
                        new
                        {
                            Id = 126,
                            CreatedDate = new DateTime(2018, 12, 17, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 6,
                            Price = 79310.299m
                        },
                        new
                        {
                            Id = 127,
                            CreatedDate = new DateTime(2018, 11, 9, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 56,
                            Price = 62157.3822m
                        },
                        new
                        {
                            Id = 128,
                            CreatedDate = new DateTime(2018, 12, 11, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 90,
                            Price = 99144.1536m
                        },
                        new
                        {
                            Id = 129,
                            CreatedDate = new DateTime(2019, 1, 7, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 79,
                            Price = 42725.295m
                        },
                        new
                        {
                            Id = 130,
                            CreatedDate = new DateTime(2019, 3, 28, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 2,
                            Price = 66231.1274m
                        },
                        new
                        {
                            Id = 131,
                            CreatedDate = new DateTime(2018, 10, 6, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 37,
                            Price = 78204.1177m
                        },
                        new
                        {
                            Id = 132,
                            CreatedDate = new DateTime(2019, 6, 26, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 8,
                            Price = 74825.226m
                        },
                        new
                        {
                            Id = 133,
                            CreatedDate = new DateTime(2018, 10, 10, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 14,
                            Price = 41415.3241m
                        },
                        new
                        {
                            Id = 134,
                            CreatedDate = new DateTime(2018, 11, 6, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 29,
                            Price = 54135.3976m
                        },
                        new
                        {
                            Id = 135,
                            CreatedDate = new DateTime(2019, 2, 9, 1, 24, 53, 682, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 21,
                            Price = 8747.476m
                        },
                        new
                        {
                            Id = 136,
                            CreatedDate = new DateTime(2018, 11, 16, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 57,
                            Price = 96702.999m
                        },
                        new
                        {
                            Id = 137,
                            CreatedDate = new DateTime(2018, 12, 10, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 48,
                            Price = 68464.3597m
                        },
                        new
                        {
                            Id = 138,
                            CreatedDate = new DateTime(2019, 6, 23, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 18,
                            Price = 78039.2190m
                        },
                        new
                        {
                            Id = 139,
                            CreatedDate = new DateTime(2018, 11, 29, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 22,
                            Price = 15260.3396m
                        },
                        new
                        {
                            Id = 140,
                            CreatedDate = new DateTime(2019, 1, 18, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 9,
                            Price = 12865.3883m
                        },
                        new
                        {
                            Id = 141,
                            CreatedDate = new DateTime(2019, 2, 27, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 5,
                            Price = 75102.3205m
                        },
                        new
                        {
                            Id = 142,
                            CreatedDate = new DateTime(2018, 11, 20, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 3,
                            Price = 85538.2898m
                        },
                        new
                        {
                            Id = 143,
                            CreatedDate = new DateTime(2019, 6, 3, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 55,
                            Price = 28043.630m
                        },
                        new
                        {
                            Id = 144,
                            CreatedDate = new DateTime(2018, 11, 18, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 14,
                            Price = 77479.2974m
                        },
                        new
                        {
                            Id = 145,
                            CreatedDate = new DateTime(2018, 11, 23, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 64,
                            Price = 45340.3715m
                        },
                        new
                        {
                            Id = 146,
                            CreatedDate = new DateTime(2018, 9, 27, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 100,
                            Price = 22485.2894m
                        },
                        new
                        {
                            Id = 147,
                            CreatedDate = new DateTime(2019, 4, 21, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 80,
                            Price = 72232.2992m
                        },
                        new
                        {
                            Id = 148,
                            CreatedDate = new DateTime(2019, 4, 13, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 46,
                            Price = 11707.3038m
                        },
                        new
                        {
                            Id = 149,
                            CreatedDate = new DateTime(2018, 12, 11, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 68,
                            Price = 5074.1243m
                        },
                        new
                        {
                            Id = 150,
                            CreatedDate = new DateTime(2018, 10, 15, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 28,
                            Price = 26026.143m
                        },
                        new
                        {
                            Id = 151,
                            CreatedDate = new DateTime(2019, 1, 12, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 23,
                            Price = 30874.1045m
                        },
                        new
                        {
                            Id = 152,
                            CreatedDate = new DateTime(2019, 3, 21, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 19,
                            Price = 21080.3796m
                        },
                        new
                        {
                            Id = 153,
                            CreatedDate = new DateTime(2018, 11, 13, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 63,
                            Price = 37430.2172m
                        },
                        new
                        {
                            Id = 154,
                            CreatedDate = new DateTime(2019, 6, 30, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 98,
                            Price = 39032.2889m
                        },
                        new
                        {
                            Id = 155,
                            CreatedDate = new DateTime(2019, 2, 20, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 100,
                            Price = 17513.1775m
                        },
                        new
                        {
                            Id = 156,
                            CreatedDate = new DateTime(2019, 2, 3, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 94,
                            Price = 23140.2312m
                        },
                        new
                        {
                            Id = 157,
                            CreatedDate = new DateTime(2019, 4, 17, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 9,
                            Price = 94516.2765m
                        },
                        new
                        {
                            Id = 158,
                            CreatedDate = new DateTime(2019, 3, 20, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 35,
                            Price = 56763.3922m
                        },
                        new
                        {
                            Id = 159,
                            CreatedDate = new DateTime(2018, 10, 6, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 70,
                            Price = 43895.94m
                        },
                        new
                        {
                            Id = 160,
                            CreatedDate = new DateTime(2019, 2, 28, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 31,
                            Price = 77622.1026m
                        },
                        new
                        {
                            Id = 161,
                            CreatedDate = new DateTime(2019, 6, 3, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 82,
                            Price = 3556.3191m
                        },
                        new
                        {
                            Id = 162,
                            CreatedDate = new DateTime(2018, 12, 4, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 36,
                            Price = 54073.634m
                        },
                        new
                        {
                            Id = 163,
                            CreatedDate = new DateTime(2019, 4, 29, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 8,
                            Price = 89418.973m
                        },
                        new
                        {
                            Id = 164,
                            CreatedDate = new DateTime(2019, 1, 3, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 35,
                            Price = 52756.3746m
                        },
                        new
                        {
                            Id = 165,
                            CreatedDate = new DateTime(2018, 12, 8, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 44,
                            Price = 78224.82m
                        },
                        new
                        {
                            Id = 166,
                            CreatedDate = new DateTime(2018, 11, 18, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 56,
                            Price = 49676.3366m
                        },
                        new
                        {
                            Id = 167,
                            CreatedDate = new DateTime(2019, 5, 13, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 58,
                            Price = 58889.371m
                        },
                        new
                        {
                            Id = 168,
                            CreatedDate = new DateTime(2018, 12, 3, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 31,
                            Price = 66220.1958m
                        },
                        new
                        {
                            Id = 169,
                            CreatedDate = new DateTime(2019, 4, 8, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 97,
                            Price = 59066.3624m
                        },
                        new
                        {
                            Id = 170,
                            CreatedDate = new DateTime(2018, 12, 13, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 93,
                            Price = 35020.2948m
                        },
                        new
                        {
                            Id = 171,
                            CreatedDate = new DateTime(2019, 1, 17, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 63,
                            Price = 76731.210m
                        },
                        new
                        {
                            Id = 172,
                            CreatedDate = new DateTime(2019, 1, 24, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 96,
                            Price = 56841.37m
                        },
                        new
                        {
                            Id = 173,
                            CreatedDate = new DateTime(2019, 5, 6, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 99,
                            Price = 69734.2587m
                        },
                        new
                        {
                            Id = 174,
                            CreatedDate = new DateTime(2018, 12, 27, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 15,
                            Price = 77844.123m
                        },
                        new
                        {
                            Id = 175,
                            CreatedDate = new DateTime(2018, 12, 7, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 51,
                            Price = 18043.546m
                        },
                        new
                        {
                            Id = 176,
                            CreatedDate = new DateTime(2019, 5, 27, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 34,
                            Price = 32077.108m
                        },
                        new
                        {
                            Id = 177,
                            CreatedDate = new DateTime(2018, 12, 3, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 8,
                            Price = 53474.15m
                        },
                        new
                        {
                            Id = 178,
                            CreatedDate = new DateTime(2019, 6, 12, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 58,
                            Price = 27.2043m
                        },
                        new
                        {
                            Id = 179,
                            CreatedDate = new DateTime(2018, 11, 5, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 71,
                            Price = 72066.208m
                        },
                        new
                        {
                            Id = 180,
                            CreatedDate = new DateTime(2018, 9, 18, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 15,
                            Price = 5499.523m
                        },
                        new
                        {
                            Id = 181,
                            CreatedDate = new DateTime(2019, 3, 8, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 40,
                            Price = 1564.1814m
                        },
                        new
                        {
                            Id = 182,
                            CreatedDate = new DateTime(2019, 2, 7, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 77,
                            Price = 93999.617m
                        },
                        new
                        {
                            Id = 183,
                            CreatedDate = new DateTime(2018, 9, 16, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 14,
                            Price = 94715.1559m
                        },
                        new
                        {
                            Id = 184,
                            CreatedDate = new DateTime(2018, 12, 8, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 91,
                            Price = 98918.3409m
                        },
                        new
                        {
                            Id = 185,
                            CreatedDate = new DateTime(2018, 11, 29, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 19,
                            Price = 2915.312m
                        },
                        new
                        {
                            Id = 186,
                            CreatedDate = new DateTime(2019, 1, 26, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 27,
                            Price = 38988.2131m
                        },
                        new
                        {
                            Id = 187,
                            CreatedDate = new DateTime(2019, 4, 29, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 36,
                            Price = 67351.156m
                        },
                        new
                        {
                            Id = 188,
                            CreatedDate = new DateTime(2018, 10, 21, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 100,
                            Price = 48917.3932m
                        },
                        new
                        {
                            Id = 189,
                            CreatedDate = new DateTime(2019, 3, 28, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 94,
                            Price = 22938.2125m
                        },
                        new
                        {
                            Id = 190,
                            CreatedDate = new DateTime(2018, 9, 21, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 19,
                            Price = 46136.989m
                        },
                        new
                        {
                            Id = 191,
                            CreatedDate = new DateTime(2019, 2, 10, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 87,
                            Price = 46494.1986m
                        },
                        new
                        {
                            Id = 192,
                            CreatedDate = new DateTime(2019, 4, 3, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 62,
                            Price = 75613.2582m
                        },
                        new
                        {
                            Id = 193,
                            CreatedDate = new DateTime(2019, 6, 2, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 29,
                            Price = 69987.1879m
                        },
                        new
                        {
                            Id = 194,
                            CreatedDate = new DateTime(2019, 4, 11, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 24,
                            Price = 30687.2340m
                        },
                        new
                        {
                            Id = 195,
                            CreatedDate = new DateTime(2019, 2, 25, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 48,
                            Price = 9254.605m
                        },
                        new
                        {
                            Id = 196,
                            CreatedDate = new DateTime(2018, 12, 9, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 3,
                            Price = 76894.2154m
                        },
                        new
                        {
                            Id = 197,
                            CreatedDate = new DateTime(2019, 2, 2, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 3,
                            Price = 85119.877m
                        },
                        new
                        {
                            Id = 198,
                            CreatedDate = new DateTime(2019, 2, 13, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 1,
                            Price = 72156.1254m
                        },
                        new
                        {
                            Id = 199,
                            CreatedDate = new DateTime(2019, 6, 22, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 54,
                            Price = 11254.1655m
                        },
                        new
                        {
                            Id = 200,
                            CreatedDate = new DateTime(2018, 9, 21, 1, 24, 53, 683, DateTimeKind.Local).AddTicks(7968),
                            CustomerId = 99,
                            Price = 6230.1230m
                        });
                });

            modelBuilder.Entity("Shop.Domain.Entities.Order", b =>
                {
                    b.HasOne("Shop.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");
                });
#pragma warning restore 612, 618
        }
    }
}
